/* ================================================================
 * Exam Idioms Data - Dữ liệu từ vựng trích từ đề thi thực tế
 * File: js/exam_idioms_data.js
 * Version: 1.0.0
 * ================================================================ */

const examIdiomData = {};

// ---------------------------------------------------------------
// EXAM TOPICS CONFIG
// ---------------------------------------------------------------
const EXAM_TOPICS = [
  {
    id: 'tongHop',
    name: 'TỔNG HỢP CÁC ĐỀ THI',
    icon: '📚',
    description: 'Sở Hà Nội 2026, Đề 25, Đề 03, KS T1/2026, VIP90 Đề 12 & 15 (88 cụm từ)',
    color: '#8b5cf6'
  }
];

// ---------------------------------------------------------------
// TOPIC: Tổng hợp tất cả các đề thi
// ---------------------------------------------------------------
examIdiomData.tongHop = [
  // ===== PHRASAL VERBS =====
  {
    phrase: 'gravitate towards',
    type: 'phrasal_verb',
    meaning_vi: 'Bị hút về phía, có xu hướng hướng tới',
    cambridge_def: 'to be attracted to or move towards something or someone',
    example_en: 'People tend to gravitate towards others with similar interests.',
    example_vi: 'Mọi người có xu hướng bị hút về phía những người có cùng sở thích.',
    exam_context: '…prompting many to gravitate towards sugary snacks.',
    sentence: 'Under acute stress, many people ______ sugary snacks for quick energy.',
    options: ['abstain from', 'derive from', 'gravitate towards', 'predispose to'],
    correct_index: 2,
    sentence_explanation: 'Khi bị stress, não cần thêm năng lượng nên nhiều người có xu hướng hướng tới đồ ngọt.'
  },
  {
    phrase: 'abstain from',
    type: 'phrasal_verb',
    meaning_vi: 'Kiêng, tránh, nhịn (không làm điều gì)',
    cambridge_def: 'to not do something, especially something enjoyable, that you think might be bad',
    example_en: 'He took a vow to abstain from alcohol.',
    example_vi: 'Anh ấy đã thề sẽ kiêng rượu.',
    exam_context: 'Đáp án nhiễu — trái nghĩa với "gravitate towards" (Q7)',
    sentence: 'Doctors advise patients to ______ fatty foods to maintain good health.',
    options: ['gravitate towards', 'abstain from', 'account for', 'end up'],
    correct_index: 1,
    sentence_explanation: 'Bác sĩ khuyên bệnh nhân kiêng/tránh đồ ăn nhiều chất béo để duy trì sức khỏe.'
  },
  {
    phrase: 'step up',
    type: 'phrasal_verb',
    meaning_vi: 'Tăng cường, đẩy mạnh',
    cambridge_def: 'to increase the size, amount, or speed of something',
    example_en: 'The police have stepped up their efforts to fight crime.',
    example_vi: 'Cảnh sát đã tăng cường nỗ lực chống tội phạm.',
    exam_context: 'Local authorities have stepped up security arrangements… (Q33)',
    sentence: 'Local authorities have ______ security arrangements to ensure a safe festival.',
    options: ['stepped up', 'used up', 'turned up', 'ended up'],
    correct_index: 0,
    sentence_explanation: 'Chính quyền địa phương đã tăng cường các sắp xếp an ninh để đảm bảo lễ hội an toàn.'
  },
  {
    phrase: 'use up',
    type: 'phrasal_verb',
    meaning_vi: 'Dùng hết, cạn kiệt',
    cambridge_def: 'to finish a supply of something',
    example_en: 'Don\'t use up all the hot water!',
    example_vi: 'Đừng dùng hết nước nóng!',
    exam_context: 'Đáp án nhiễu (Q33)',
    sentence: 'We\'ve ______ all the paper in the printer. Could you get some more?',
    options: ['stepped up', 'used up', 'set aside', 'turned up'],
    correct_index: 1,
    sentence_explanation: 'Chúng tôi đã dùng hết giấy trong máy in. Bạn lấy thêm được không?'
  },
  {
    phrase: 'turn up',
    type: 'phrasal_verb',
    meaning_vi: 'Xuất hiện, đến (bất ngờ); được tìm thấy',
    cambridge_def: 'to arrive or appear somewhere, usually unexpectedly',
    example_en: 'She turned up an hour late.',
    example_vi: 'Cô ấy xuất hiện muộn một tiếng.',
    exam_context: 'Đáp án nhiễu (Q33)',
    sentence: 'We were worried when Tom didn\'t ______ for the meeting on time.',
    options: ['step up', 'end up', 'turn up', 'use up'],
    correct_index: 2,
    sentence_explanation: 'Chúng tôi lo lắng khi Tom không xuất hiện đúng giờ cho cuộc họp.'
  },
  {
    phrase: 'end up',
    type: 'phrasal_verb',
    meaning_vi: 'Cuối cùng rơi vào (tình huống/nơi nào đó)',
    cambridge_def: 'to finally be in a particular place or situation',
    example_en: 'They\'re going to end up in trouble.',
    example_vi: 'Họ sẽ cuối cùng gặp rắc rối.',
    exam_context: 'Đáp án nhiễu (Q33)',
    sentence: 'If you keep spending like that, you\'ll ______ with no money at all.',
    options: ['turn up', 'step up', 'use up', 'end up'],
    correct_index: 3,
    sentence_explanation: 'Nếu bạn tiếp tục tiêu xài như vậy, cuối cùng bạn sẽ không còn tiền.'
  },
  {
    phrase: 'take up',
    type: 'phrasal_verb',
    meaning_vi: 'Bắt đầu (công việc/hoạt động mới); chiếm (thời gian/không gian)',
    cambridge_def: 'to start doing a particular job or activity',
    example_en: 'He\'s taken up jogging.',
    example_vi: 'Anh ấy đã bắt đầu chạy bộ.',
    exam_context: 'You\'ve taken up a new job or started a new course… (Q24)',
    sentence: 'After retiring, my grandmother ______ painting as a new hobby.',
    options: ['took up', 'gave up', 'set aside', 'turned up'],
    correct_index: 0,
    sentence_explanation: 'Sau khi nghỉ hưu, bà tôi đã bắt đầu vẽ tranh như một sở thích mới.'
  },
  {
    phrase: 'get along',
    type: 'phrasal_verb',
    meaning_vi: 'Hòa hợp, hợp nhau',
    cambridge_def: 'if two or more people get along, they like each other and are friendly to each other',
    example_en: 'I don\'t really get along with my sister\'s husband.',
    example_vi: 'Tôi không thực sự hợp nhau với chồng chị gái tôi.',
    exam_context: '…I think you two will get along. (Q5)',
    sentence: 'Don\'t worry. He\'s very friendly, so I think you two will ______.',
    options: ['get along', 'look forward to', 'take up', 'single out'],
    correct_index: 0,
    sentence_explanation: 'Đừng lo. Anh ấy rất thân thiện nên tôi nghĩ hai bạn sẽ hòa hợp.'
  },
  {
    phrase: 'look forward to',
    type: 'phrasal_verb',
    meaning_vi: 'Mong chờ, trông đợi',
    cambridge_def: 'to feel pleased and excited about something that is going to happen',
    example_en: 'I\'m really looking forward to my holiday.',
    example_vi: 'Tôi thực sự mong chờ kỳ nghỉ của mình.',
    exam_context: 'I look forward to your prompt response. (Q1)',
    sentence: 'I am ______ hearing from you soon regarding my application.',
    options: ['looking forward to', 'getting along with', 'setting aside', 'working towards'],
    correct_index: 0,
    sentence_explanation: 'Tôi mong chờ sớm nhận được hồi âm từ bạn về đơn ứng tuyển của tôi.'
  },
  {
    phrase: 'set aside',
    type: 'phrasal_verb',
    meaning_vi: 'Dành riêng (thời gian, tiền bạc) cho mục đích cụ thể',
    cambridge_def: 'to save something, usually time or money, for a special purpose',
    example_en: 'He sets aside some time every day to read to his children.',
    example_vi: 'Anh ấy dành ra thời gian mỗi ngày để đọc sách cho con.',
    exam_context: 'Setting aside a little time for careful planning… (Q27)',
    sentence: 'You should ______ some time every day for physical exercise.',
    options: ['take up', 'set aside', 'end up', 'step up'],
    correct_index: 1,
    sentence_explanation: 'Bạn nên dành riêng một chút thời gian mỗi ngày cho việc tập thể dục.'
  },
  {
    phrase: 'single out',
    type: 'phrasal_verb',
    meaning_vi: 'Chọn ra, nhắm vào (một cá nhân từ nhóm)',
    cambridge_def: 'to choose one person or thing from a group for special attention',
    example_en: 'It\'s not fair the way my sister is always singled out for criticism.',
    example_vi: 'Không công bằng khi chị tôi luôn bị chọn ra để chỉ trích.',
    exam_context: 'Singling out one individual risks oversimplifying a broader issue… (Passage 2)',
    sentence: 'It\'s unfair to ______ one student for punishment when the whole class was noisy.',
    options: ['single out', 'step up', 'account for', 'compensate for'],
    correct_index: 0,
    sentence_explanation: 'Không công bằng khi chọn ra một học sinh để phạt trong khi cả lớp đều ồn.'
  },
  {
    phrase: 'account for',
    type: 'phrasal_verb',
    meaning_vi: 'Chiếm (tỷ lệ); giải thích (lý do)',
    cambridge_def: 'to form the total of something; to explain the reason for something',
    example_en: 'Students account for the majority of our customers.',
    example_vi: 'Sinh viên chiếm phần lớn khách hàng của chúng tôi.',
    exam_context: '…our brain accounts for just 2 percent of our body weight… (Passage 1)',
    sentence: 'Although the brain ______ only 2% of body weight, it uses 20% of our energy.',
    options: ['derives from', 'accounts for', 'compensates for', 'gravitates towards'],
    correct_index: 1,
    sentence_explanation: 'Mặc dù não chỉ chiếm 2% trọng lượng cơ thể, nó sử dụng 20% năng lượng.'
  },
  {
    phrase: 'compensate for',
    type: 'phrasal_verb',
    meaning_vi: 'Bù đắp, đền bù cho',
    cambridge_def: 'to provide something good or useful in place of something that has been lost',
    example_en: 'Nothing can compensate for the loss of a loved one.',
    example_vi: 'Không gì có thể bù đắp cho việc mất đi người thân.',
    exam_context: '…allows individuals to compensate for emissions… (Passage 2)',
    sentence: 'Carbon offsetting allows people to ______ their emissions by funding green projects.',
    options: ['account for', 'compensate for', 'derive from', 'abstain from'],
    correct_index: 1,
    sentence_explanation: 'Bù đắp carbon cho phép mọi người bù đắp lượng khí thải bằng cách tài trợ các dự án xanh.'
  },
  {
    phrase: 'derive from',
    type: 'phrasal_verb',
    meaning_vi: 'Bắt nguồn từ; thu được từ',
    cambridge_def: 'to come from something; to get something from something else',
    example_en: 'She derives great pleasure from painting.',
    example_vi: 'Cô ấy thu được niềm vui lớn từ việc vẽ tranh.',
    exam_context: 'Đáp án nhiễu (Q7)',
    sentence: 'The English word "olive" is ______ the Latin word "oliva".',
    options: ['derived from', 'accounted for', 'compensated for', 'abstained from'],
    correct_index: 0,
    sentence_explanation: 'Từ "olive" trong tiếng Anh bắt nguồn từ từ "oliva" trong tiếng Latin.'
  },
  {
    phrase: 'work towards',
    type: 'phrasal_verb',
    meaning_vi: 'Nỗ lực hướng tới, phấn đấu đạt được',
    cambridge_def: 'to try to achieve something',
    example_en: 'We need to work towards an agreement.',
    example_vi: 'Chúng ta cần nỗ lực hướng tới một thỏa thuận.',
    exam_context: '…particularly when working towards a deadline. (Passage Leaflet)',
    sentence: 'All team members are ______ the same goal of finishing the project on time.',
    options: ['looking forward to', 'working towards', 'getting along with', 'setting aside'],
    correct_index: 1,
    sentence_explanation: 'Tất cả thành viên nhóm đang nỗ lực hướng tới cùng mục tiêu hoàn thành dự án đúng hạn.'
  },
  {
    phrase: 'feel like',
    type: 'phrasal_verb',
    meaning_vi: 'Muốn, thích (làm gì đó)',
    cambridge_def: 'to want to have or do something',
    example_en: 'Do you feel like going out tonight?',
    example_vi: 'Bạn có muốn đi chơi tối nay không?',
    exam_context: '…do you feel like studying tomorrow…? (Q3)',
    sentence: 'After a long day at work, I don\'t ______ cooking dinner.',
    options: ['feel like', 'get along', 'look forward to', 'take up'],
    correct_index: 0,
    sentence_explanation: 'Sau một ngày dài làm việc, tôi không muốn nấu bữa tối.'
  },

  // ===== IDIOMS =====
  {
    phrase: 'second nature',
    type: 'idiom',
    meaning_vi: 'Bản năng thứ hai, thói quen tự nhiên (làm mà không cần suy nghĩ)',
    cambridge_def: 'If something is second nature to you, you are so familiar with it that you can do it easily without needing to think very much about it.',
    example_en: 'Driving is second nature to him.',
    example_vi: 'Lái xe là bản năng thứ hai của anh ấy.',
    exam_context: 'When positive behaviours become second nature, they require less effort… (Q28)',
    sentence: 'After years of practice, playing the piano became ______ to her.',
    options: ['first instinct', 'second nature', 'third habit', 'main routine'],
    correct_index: 1,
    sentence_explanation: 'Sau nhiều năm luyện tập, chơi piano trở thành bản năng thứ hai của cô ấy.'
  },
  {
    phrase: 'eat that frog',
    type: 'idiom',
    meaning_vi: 'Hãy làm việc khó nhất/khó chịu nhất trước',
    cambridge_def: 'A metaphorical expression meaning to tackle your most challenging or important task first thing in the morning.',
    example_en: 'If you eat that frog first, you\'ll feel more productive all day.',
    example_vi: 'Nếu bạn làm việc khó nhất trước, bạn sẽ cảm thấy năng suất hơn cả ngày.',
    exam_context: 'Tiêu đề bài đọc: Eat That Frog! (Passage Leaflet)',
    sentence: 'Brian Tracy advises people to "______" — do their hardest task at the start of the day.',
    options: ['eat that frog', 'kill two birds', 'break the ice', 'bite the bullet'],
    correct_index: 0,
    sentence_explanation: 'Brian Tracy khuyên mọi người "ăn con ếch" — làm việc khó nhất vào đầu ngày.'
  },

  // ===== COLLOCATIONS =====
  {
    phrase: 'reach one\'s full potential',
    type: 'collocation',
    meaning_vi: 'Phát huy hết tiềm năng',
    cambridge_def: 'to become the best that you are capable of being',
    example_en: 'I don\'t feel I\'m achieving my full potential in my present job.',
    example_vi: 'Tôi không cảm thấy mình đang phát huy hết tiềm năng ở công việc hiện tại.',
    exam_context: '…help you reach your full potential and avoid burnout. (Passage Leaflet)',
    sentence: 'Good habits can help you ______ and avoid burnout.',
    options: ['avoid burnout', 'reach your full potential', 'take immediate action', 'make a difference'],
    correct_index: 1,
    sentence_explanation: 'Những thói quen tốt có thể giúp bạn phát huy hết tiềm năng và tránh kiệt sức.'
  },
  {
    phrase: 'avoid burnout',
    type: 'collocation',
    meaning_vi: 'Tránh kiệt sức',
    cambridge_def: 'burnout: the state of having no energy or enthusiasm because of working too hard',
    example_en: 'She suffered burnout after years of overwork.',
    example_vi: 'Cô ấy bị kiệt sức sau nhiều năm làm việc quá sức.',
    exam_context: '…reach your full potential and avoid burnout. (Passage Leaflet)',
    sentence: 'Taking regular breaks is important to ______ when studying for exams.',
    options: ['reach potential', 'take action', 'avoid burnout', 'make a difference'],
    correct_index: 2,
    sentence_explanation: 'Nghỉ ngơi đều đặn rất quan trọng để tránh kiệt sức khi ôn thi.'
  },
  {
    phrase: 'sense of achievement',
    type: 'collocation',
    meaning_vi: 'Cảm giác thành tựu',
    cambridge_def: 'a feeling that you have succeeded in doing something very good and difficult',
    example_en: 'Completing the marathon gave her a great sense of achievement.',
    example_vi: 'Hoàn thành cuộc marathon mang lại cho cô ấy cảm giác thành tựu lớn.',
    exam_context: 'Completing it early gives you a strong sense of achievement… (Passage Leaflet)',
    sentence: 'Finishing a difficult task early gives you a strong ______.',
    options: ['sense of achievement', 'career prospects', 'carbon footprint', 'root cause'],
    correct_index: 0,
    sentence_explanation: 'Hoàn thành một việc khó sớm mang lại cho bạn cảm giác thành tựu mạnh mẽ.'
  },
  {
    phrase: 'take immediate action',
    type: 'collocation',
    meaning_vi: 'Hành động ngay lập tức',
    cambridge_def: 'take action: to do something to deal with a problem',
    example_en: 'We must take immediate action to deal with this problem.',
    example_vi: 'Chúng ta phải hành động ngay lập tức để giải quyết vấn đề này.',
    exam_context: 'Taking immediate action is essential for long-term success. (Q26)',
    sentence: '______ is essential for long-term success, rather than waiting for the perfect moment.',
    options: ['Making immediate action', 'Taking immediate action', 'Doing immediate action', 'Getting immediate action'],
    correct_index: 1,
    sentence_explanation: 'Hành động ngay lập tức là cần thiết cho thành công lâu dài, thay vì chờ đợi thời điểm hoàn hảo.'
  },
  {
    phrase: 'make a difference',
    type: 'collocation',
    meaning_vi: 'Tạo ra sự khác biệt, có tác động tích cực',
    cambridge_def: 'to improve a situation; to have an effect on a person or situation',
    example_en: 'Exercising regularly can make a big difference to your health.',
    example_vi: 'Tập thể dục đều đặn có thể tạo ra sự khác biệt lớn cho sức khỏe.',
    exam_context: '…careful planning can also make a difference. (Passage Leaflet)',
    sentence: 'Careful planning can ______ to your productivity at work.',
    options: ['take action', 'make a difference', 'set aside', 'step up'],
    correct_index: 1,
    sentence_explanation: 'Lập kế hoạch cẩn thận có thể tạo ra sự khác biệt cho năng suất làm việc.'
  },
  {
    phrase: 'career prospects',
    type: 'collocation',
    meaning_vi: 'Triển vọng nghề nghiệp',
    cambridge_def: 'prospects: the possibility of being successful, especially at work',
    example_en: 'She has excellent career prospects.',
    example_vi: 'Cô ấy có triển vọng nghề nghiệp xuất sắc.',
    exam_context: 'Observing successful people can improve your career prospects. (Passage Leaflet)',
    sentence: 'Developing new skills can significantly improve your ______.',
    options: ['career prospects', 'carbon footprint', 'root cause', 'sense of achievement'],
    correct_index: 0,
    sentence_explanation: 'Phát triển kỹ năng mới có thể cải thiện đáng kể triển vọng nghề nghiệp của bạn.'
  },
  {
    phrase: 'carbon footprint',
    type: 'collocation',
    meaning_vi: 'Dấu chân carbon (lượng CO₂ thải ra)',
    cambridge_def: 'the amount of carbon dioxide that a person, organization, building, etc. produces',
    example_en: 'We all need to reduce our carbon footprint.',
    example_vi: 'Tất cả chúng ta cần giảm dấu chân carbon.',
    exam_context: '…the celebrity with the largest carbon footprint… (Passage 2)',
    sentence: 'Taylor Swift was ranked as the celebrity with the largest ______.',
    options: ['carbon offsetting', 'carbon footprint', 'root cause', 'career prospects'],
    correct_index: 1,
    sentence_explanation: 'Taylor Swift được xếp hạng là người nổi tiếng có dấu chân carbon lớn nhất.'
  },
  {
    phrase: 'carbon offsetting',
    type: 'collocation',
    meaning_vi: 'Bù đắp carbon',
    cambridge_def: 'the process of trying to reduce damage caused by releasing CO₂ by doing other things that remove CO₂',
    example_en: 'Carbon offsetting involves investing in projects that reduce emissions.',
    example_vi: 'Bù đắp carbon bao gồm đầu tư vào các dự án giảm phát thải.',
    exam_context: 'One popular approach is carbon offsetting… (Passage 2)',
    sentence: '______ allows individuals to compensate for emissions by funding environmental initiatives.',
    options: ['Carbon footprint', 'Carbon offsetting', 'Root cause', 'Career prospects'],
    correct_index: 1,
    sentence_explanation: 'Bù đắp carbon cho phép cá nhân bù đắp lượng khí thải bằng cách tài trợ sáng kiến môi trường.'
  },
  {
    phrase: 'root cause',
    type: 'collocation',
    meaning_vi: 'Nguyên nhân gốc rễ',
    cambridge_def: 'the main reason for a problem',
    example_en: 'We need to identify the root cause of the problem.',
    example_vi: 'Chúng ta cần xác định nguyên nhân gốc rễ của vấn đề.',
    exam_context: '…these efforts do little to address the root causes of excess carbon emissions. (Passage 2)',
    sentence: 'To truly solve a problem, you need to find its ______ rather than just treating symptoms.',
    options: ['sense of achievement', 'carbon footprint', 'root cause', 'career prospects'],
    correct_index: 2,
    sentence_explanation: 'Để thực sự giải quyết vấn đề, bạn cần tìm nguyên nhân gốc rễ thay vì chỉ xử lý triệu chứng.'
  },
  {
    phrase: 'predispose to',
    type: 'collocation',
    meaning_vi: 'Khiến ai có khuynh hướng/dễ mắc phải',
    cambridge_def: 'to make someone more likely to think, behave, or suffer from something in a particular way',
    example_en: 'Smoking predisposes you to lung cancer.',
    example_vi: 'Hút thuốc khiến bạn dễ mắc ung thư phổi.',
    exam_context: 'Đáp án nhiễu (Q7)',
    sentence: 'A poor diet can ______ you ______ various health problems.',
    options: ['predispose…to', 'abstain…from', 'derive…from', 'compensate…for'],
    correct_index: 0,
    sentence_explanation: 'Chế độ ăn kém có thể khiến bạn dễ mắc các vấn đề sức khỏe khác nhau.'
  },
  {
    phrase: 'incline to',
    type: 'collocation',
    meaning_vi: 'Có xu hướng, nghiêng về',
    cambridge_def: 'to have an opinion, or make someone think or behave in a particular way',
    example_en: 'I incline to the view that peace can be achieved.',
    example_vi: 'Tôi nghiêng về quan điểm rằng hòa bình có thể đạt được.',
    exam_context: 'Đáp án nhiễu (Q7)',
    sentence: 'I am ______ agree with you on this matter.',
    options: ['inclined to', 'predisposed to', 'derived from', 'abstained from'],
    correct_index: 0,
    sentence_explanation: 'Tôi có xu hướng đồng ý với bạn về vấn đề này.'
  },

  // ===== FIXED PHRASES =====
  {
    phrase: 'under warranty',
    type: 'fixed_phrase',
    meaning_vi: 'Còn bảo hành',
    cambridge_def: 'warranty: a written promise from a company to repair or replace a product that develops a fault',
    example_en: 'The washing machine is still under warranty.',
    example_vi: 'Máy giặt vẫn còn bảo hành.',
    exam_context: '…this is a brand-new product and still under warranty… (Q1)',
    sentence: 'As this product is still ______, the manufacturer will pay for repairs.',
    options: ['under warranty', 'under scrutiny', 'on a larger scale', 'to some extent'],
    correct_index: 0,
    sentence_explanation: 'Vì sản phẩm này vẫn còn bảo hành, nhà sản xuất sẽ trả tiền sửa chữa.'
  },
  {
    phrase: 'back to normal',
    type: 'fixed_phrase',
    meaning_vi: 'Trở lại bình thường',
    cambridge_def: 'as something was before a particular event or situation',
    example_en: 'Things are slowly getting back to normal after the strike.',
    example_vi: 'Mọi thứ đang dần trở lại bình thường sau cuộc đình công.',
    exam_context: 'Their performance went back to normal after consuming carbohydrates. (Passage 1)',
    sentence: 'After the storm, it took a week for everything to get ______.',
    options: ['back to normal', 'under scrutiny', 'to some extent', 'in any meaningful sense'],
    correct_index: 0,
    sentence_explanation: 'Sau cơn bão, phải mất một tuần để mọi thứ trở lại bình thường.'
  },
  {
    phrase: 'under constant scrutiny',
    type: 'fixed_phrase',
    meaning_vi: 'Bị giám sát/xem xét kỹ lưỡng',
    cambridge_def: 'scrutiny: the careful and detailed examination of something in order to get information about it',
    example_en: 'The company came under scrutiny after allegations of fraud.',
    example_vi: 'Công ty bị giám sát kỹ lưỡng sau các cáo buộc gian lận.',
    exam_context: 'Celebrity air travel remains under constant scrutiny… (Passage 2)',
    sentence: 'Celebrity air travel remains ______, regardless of public sentiment.',
    options: ['under warranty', 'under constant scrutiny', 'back to normal', 'to some extent'],
    correct_index: 1,
    sentence_explanation: 'Việc di chuyển bằng máy bay của người nổi tiếng vẫn bị giám sát kỹ lưỡng, bất kể dư luận.'
  },

  // ===== PREPOSITIONAL PHRASES =====
  {
    phrase: 'to some extent',
    type: 'prepositional_phrase',
    meaning_vi: 'Ở một mức độ nào đó, phần nào',
    cambridge_def: 'partly',
    example_en: 'To some extent, she was responsible for the accident.',
    example_vi: 'Ở một mức độ nào đó, cô ấy phải chịu trách nhiệm cho tai nạn.',
    exam_context: 'Carbon emissions are, to some extent, unavoidable… (Passage 2)',
    sentence: 'Carbon emissions are, ______, unavoidable for public figures who travel frequently.',
    options: ['on a larger scale', 'in any meaningful sense', 'to some extent', 'under scrutiny'],
    correct_index: 2,
    sentence_explanation: 'Phát thải carbon, ở một mức độ nào đó, là không thể tránh khỏi với người nổi tiếng di chuyển thường xuyên.'
  },
  {
    phrase: 'in any meaningful sense',
    type: 'prepositional_phrase',
    meaning_vi: 'Theo bất kỳ nghĩa thực chất nào',
    cambridge_def: 'meaningful: useful, serious, or important',
    example_en: 'The policy has not changed in any meaningful sense.',
    example_vi: 'Chính sách không thay đổi theo bất kỳ nghĩa thực chất nào.',
    exam_context: '…they rarely neutralize emissions in any meaningful sense. (Passage 2)',
    sentence: 'Critics argue that carbon offsets rarely neutralize emissions ______.',
    options: ['to some extent', 'under scrutiny', 'on a larger scale', 'in any meaningful sense'],
    correct_index: 3,
    sentence_explanation: 'Các nhà phê bình cho rằng bù đắp carbon hiếm khi trung hòa phát thải theo nghĩa thực chất.'
  },
  {
    phrase: 'on a larger scale',
    type: 'prepositional_phrase',
    meaning_vi: 'Ở quy mô lớn hơn, trên phạm vi rộng hơn',
    cambridge_def: 'on a large/small scale: used for saying that something is done to a great or limited degree',
    example_en: 'We need to produce on a larger scale.',
    example_vi: 'Chúng ta cần sản xuất ở quy mô lớn hơn.',
    exam_context: 'On a larger scale, integrating media literacy education into school curricula is crucial… (Q4)',
    sentence: '______, integrating media literacy into school curricula is crucial for developing critical thinkers.',
    options: ['To some extent', 'In any meaningful sense', 'On a larger scale', 'Under scrutiny'],
    correct_index: 2,
    sentence_explanation: 'Ở quy mô lớn hơn, tích hợp giáo dục về truyền thông vào chương trình nhà trường là rất quan trọng.'
  },

  // =============================================================
  // PHẦN 2: Đề 25, Đề 03, KS T1/2026, VIP90 Đề 12 & 15
  // =============================================================
  // ===== IDIOMS =====
  {
    phrase: 'turn a blind eye (to)',
    type: 'idiom',
    meaning_vi: 'Làm ngơ, phớt lờ (điều sai trái)',
    cambridge_def: 'to ignore something that you know is wrong or illegal',
    example_en: 'Management turned a blind eye to the safety problems.',
    example_vi: 'Ban quản lý đã làm ngơ trước các vấn đề an toàn.',
    exam_context: 'Nguồn: Đề 25',
    sentence: 'The teacher ______ the students using their phones during the test.',
    options: ['turned a blind eye to', 'thought outside the box about', 'was at the forefront of', 'made a difference to'],
    correct_index: 0,
    sentence_explanation: 'Giáo viên đã làm ngơ việc học sinh sử dụng điện thoại trong bài kiểm tra.'
  },
  {
    phrase: 'think outside the box',
    type: 'idiom',
    meaning_vi: 'Suy nghĩ sáng tạo, khác biệt',
    cambridge_def: 'to think of new, different, or creative ideas rather than using the same methods',
    example_en: 'We need to think outside the box to solve this problem.',
    example_vi: 'Chúng ta cần suy nghĩ sáng tạo để giải quyết vấn đề này.',
    exam_context: 'Nguồn: VIP90 Đề 12',
    sentence: 'To find innovative solutions, employees are encouraged to ______.',
    options: ['think outside the box', 'turn a blind eye', 'pose a problem', 'draw up a plan'],
    correct_index: 0,
    sentence_explanation: 'Để tìm giải pháp sáng tạo, nhân viên được khuyến khích suy nghĩ khác biệt.'
  },
  {
    phrase: 'at the forefront of',
    type: 'idiom',
    meaning_vi: 'Đi đầu, tiên phong trong',
    cambridge_def: 'in the most important position; leading the way in something',
    example_en: 'The company is at the forefront of technology innovation.',
    example_vi: 'Công ty đi đầu trong đổi mới công nghệ.',
    exam_context: 'Nguồn: Đề 25',
    sentence: 'Japan has always been ______ technological development.',
    options: ['at the forefront of', 'in the absence of', 'at the bottom of', 'in conjunction with'],
    correct_index: 0,
    sentence_explanation: 'Nhật Bản luôn đi đầu trong phát triển công nghệ.'
  },

  // ===== PHRASAL VERBS =====
  {
    phrase: 'work out',
    type: 'phrasal_verb',
    meaning_vi: 'Tìm ra giải pháp; tính toán; tập thể dục',
    cambridge_def: 'to plan or find a solution to something; to calculate',
    example_en: 'We need to work out how to reduce costs.',
    example_vi: 'Chúng ta cần tìm ra cách giảm chi phí.',
    exam_context: 'Nguồn: Đề 25',
    sentence: 'The team is trying to ______ a solution to the budget problem.',
    options: ['work out', 'push out', 'note down', 'bring down'],
    correct_index: 0,
    sentence_explanation: 'Nhóm đang cố gắng tìm ra giải pháp cho vấn đề ngân sách.'
  },
  {
    phrase: 'push out',
    type: 'phrasal_verb',
    meaning_vi: 'Đẩy ra, buộc ai rời khỏi vị trí',
    cambridge_def: 'to force someone to leave a group or position',
    example_en: 'He was pushed out of the company after the scandal.',
    example_vi: 'Anh ấy bị buộc rời khỏi công ty sau vụ bê bối.',
    exam_context: 'Nguồn: Đề 25',
    sentence: 'Several senior managers were ______ during the restructuring.',
    options: ['pushed out', 'noted down', 'worked out', 'brought down'],
    correct_index: 0,
    sentence_explanation: 'Một số quản lý cấp cao bị buộc rời khỏi trong quá trình tái cơ cấu.'
  },
  {
    phrase: 'note down',
    type: 'phrasal_verb',
    meaning_vi: 'Ghi chép lại',
    cambridge_def: 'to write information so that you do not forget it',
    example_en: 'Let me note down your phone number.',
    example_vi: 'Để tôi ghi lại số điện thoại của bạn.',
    exam_context: 'Nguồn: Đề 25',
    sentence: 'Please ______ the key points from the lecture.',
    options: ['note down', 'bring down', 'cool down', 'pull down'],
    correct_index: 0,
    sentence_explanation: 'Hãy ghi chép lại các điểm chính từ bài giảng.'
  },
  {
    phrase: 'bring down',
    type: 'phrasal_verb',
    meaning_vi: 'Giảm xuống; lật đổ (chính phủ)',
    cambridge_def: 'to reduce something; to cause the end of a government or system',
    example_en: 'The government is trying to bring down the cost of living.',
    example_vi: 'Chính phủ đang cố gắng giảm chi phí sinh hoạt.',
    exam_context: 'Nguồn: Đề 25',
    sentence: 'New policies aim to ______ inflation rates.',
    options: ['bring down', 'push out', 'note down', 'draw up'],
    correct_index: 0,
    sentence_explanation: 'Các chính sách mới nhằm giảm tỷ lệ lạm phát.'
  },
  {
    phrase: 'cool down',
    type: 'phrasal_verb',
    meaning_vi: 'Hạ nhiệt; bình tĩnh lại',
    cambridge_def: 'to become less hot; to become calmer',
    example_en: 'Let the engine cool down before you check it.',
    example_vi: 'Hãy để động cơ nguội xuống trước khi kiểm tra.',
    exam_context: 'Nguồn: Đề 03',
    sentence: 'After the argument, she went for a walk to ______.',
    options: ['cool down', 'calm down', 'pull down', 'pass down'],
    correct_index: 0,
    sentence_explanation: 'Sau cuộc cãi vã, cô ấy đi dạo để hạ nhiệt.'
  },
  {
    phrase: 'calm down',
    type: 'phrasal_verb',
    meaning_vi: 'Bình tĩnh lại',
    cambridge_def: 'to stop feeling upset, angry, or excited',
    example_en: 'Calm down and tell me what happened.',
    example_vi: 'Bình tĩnh lại và kể cho tôi chuyện gì đã xảy ra.',
    exam_context: 'Nguồn: Đề 03',
    sentence: 'The teacher asked the students to ______ before starting the exam.',
    options: ['calm down', 'cool down', 'bring down', 'pass down'],
    correct_index: 0,
    sentence_explanation: 'Giáo viên yêu cầu học sinh bình tĩnh lại trước khi bắt đầu bài thi.'
  },
  {
    phrase: 'pull down',
    type: 'phrasal_verb',
    meaning_vi: 'Phá hủy (tòa nhà); kéo xuống',
    cambridge_def: 'to destroy a building; to move something downward',
    example_en: 'They pulled down the old factory to build apartments.',
    example_vi: 'Họ phá hủy nhà máy cũ để xây căn hộ.',
    exam_context: 'Nguồn: Đề 03',
    sentence: 'The city council decided to ______ the abandoned building.',
    options: ['pull down', 'cool down', 'note down', 'calm down'],
    correct_index: 0,
    sentence_explanation: 'Hội đồng thành phố quyết định phá hủy tòa nhà bỏ hoang.'
  },
  {
    phrase: 'pass down',
    type: 'phrasal_verb',
    meaning_vi: 'Truyền lại (cho thế hệ sau)',
    cambridge_def: 'to give or teach something to younger people',
    example_en: 'These traditions have been passed down for generations.',
    example_vi: 'Những truyền thống này đã được truyền lại qua nhiều thế hệ.',
    exam_context: 'Nguồn: Đề 03',
    sentence: 'Folk songs are ______ from generation to generation.',
    options: ['passed down', 'pulled down', 'brought down', 'cooled down'],
    correct_index: 0,
    sentence_explanation: 'Các bài dân ca được truyền lại từ thế hệ này sang thế hệ khác.'
  },
  {
    phrase: 'draw up',
    type: 'phrasal_verb',
    meaning_vi: 'Soạn thảo, lập (kế hoạch, danh sách)',
    cambridge_def: 'to prepare a plan, list, or document',
    example_en: 'The lawyer drew up the contract.',
    example_vi: 'Luật sư đã soạn thảo hợp đồng.',
    exam_context: 'Nguồn: Đề 03',
    sentence: 'The committee needs to ______ a list of candidates.',
    options: ['draw up', 'pass down', 'drown out', 'turn into'],
    correct_index: 0,
    sentence_explanation: 'Ủy ban cần lập một danh sách ứng viên.'
  },
  {
    phrase: 'turn into',
    type: 'phrasal_verb',
    meaning_vi: 'Biến thành, trở thành',
    cambridge_def: 'to change and become something different',
    example_en: 'The caterpillar turns into a butterfly.',
    example_vi: 'Con sâu bướm biến thành con bướm.',
    exam_context: 'Nguồn: Đề 03',
    sentence: 'The small village has ______ a modern city over the last decade.',
    options: ['turned into', 'drawn up', 'left behind', 'come across'],
    correct_index: 0,
    sentence_explanation: 'Ngôi làng nhỏ đã biến thành một thành phố hiện đại trong thập kỷ qua.'
  },
  {
    phrase: 'cope with',
    type: 'phrasal_verb',
    meaning_vi: 'Đối phó, xử lý (tình huống khó khăn)',
    cambridge_def: 'to deal with something difficult successfully',
    example_en: 'She found it hard to cope with the pressure of work.',
    example_vi: 'Cô ấy thấy khó đối phó với áp lực công việc.',
    exam_context: 'Nguồn: Đề 03',
    sentence: 'Students need to learn how to ______ stress during exams.',
    options: ['cope with', 'leave behind', 'drown out', 'come across'],
    correct_index: 0,
    sentence_explanation: 'Học sinh cần học cách đối phó với căng thẳng trong mùa thi.'
  },
  {
    phrase: 'leave behind',
    type: 'phrasal_verb',
    meaning_vi: 'Bỏ lại, để lại phía sau',
    cambridge_def: 'to go away from a place without taking someone or something',
    example_en: 'I left my keys behind at the restaurant.',
    example_vi: 'Tôi đã bỏ quên chìa khóa ở nhà hàng.',
    exam_context: 'Nguồn: Đề 03',
    sentence: 'She moved to the city and ______ her hometown memories.',
    options: ['left behind', 'coped with', 'turned into', 'drowned out'],
    correct_index: 0,
    sentence_explanation: 'Cô ấy chuyển đến thành phố và bỏ lại những kỷ niệm quê hương.'
  },
  {
    phrase: 'drown out',
    type: 'phrasal_verb',
    meaning_vi: 'Át đi, lấn át (âm thanh)',
    cambridge_def: 'to prevent a sound from being heard by making a louder noise',
    example_en: 'The music drowned out the sound of the traffic.',
    example_vi: 'Âm nhạc đã lấn át tiếng giao thông.',
    exam_context: 'Nguồn: Đề 03',
    sentence: 'The noise from the construction site ______ our conversation.',
    options: ['drowned out', 'left behind', 'coped with', 'drew up'],
    correct_index: 0,
    sentence_explanation: 'Tiếng ồn từ công trường đã lấn át cuộc trò chuyện của chúng tôi.'
  },
  {
    phrase: 'come across',
    type: 'phrasal_verb',
    meaning_vi: 'Tình cờ gặp, bắt gặp',
    cambridge_def: 'to find or meet someone or something by chance',
    example_en: 'I came across an old friend at the mall.',
    example_vi: 'Tôi tình cờ gặp một người bạn cũ ở trung tâm thương mại.',
    exam_context: 'Nguồn: KS T1/2026',
    sentence: 'While reading the newspaper, I ______ an interesting article about AI.',
    options: ['came across', 'ruled out', 'gave out', 'cut down on'],
    correct_index: 0,
    sentence_explanation: 'Khi đọc báo, tôi tình cờ bắt gặp một bài viết thú vị về AI.'
  },
  {
    phrase: 'rule out',
    type: 'phrasal_verb',
    meaning_vi: 'Loại trừ, loại bỏ khả năng',
    cambridge_def: 'to decide that something is impossible or not suitable',
    example_en: 'The police have not ruled out the possibility of murder.',
    example_vi: 'Cảnh sát chưa loại trừ khả năng giết người.',
    exam_context: 'Nguồn: KS T1/2026',
    sentence: 'Doctors cannot ______ the possibility of an allergic reaction.',
    options: ['rule out', 'give out', 'come across', 'stand out'],
    correct_index: 0,
    sentence_explanation: 'Bác sĩ không thể loại trừ khả năng phản ứng dị ứng.'
  },
  {
    phrase: 'give out',
    type: 'phrasal_verb',
    meaning_vi: 'Phát, phân phát; ngừng hoạt động',
    cambridge_def: 'to give something to several people; to stop working',
    example_en: 'Volunteers gave out food to the homeless.',
    example_vi: 'Tình nguyện viên phát thức ăn cho người vô gia cư.',
    exam_context: 'Nguồn: KS T1/2026',
    sentence: 'The charity ______ free meals to families in need.',
    options: ['gave out', 'ruled out', 'set in', 'stood out'],
    correct_index: 0,
    sentence_explanation: 'Tổ chức từ thiện phát bữa ăn miễn phí cho các gia đình khó khăn.'
  },
  {
    phrase: 'cut down on',
    type: 'phrasal_verb',
    meaning_vi: 'Cắt giảm, giảm bớt',
    cambridge_def: 'to reduce the amount or number of something',
    example_en: 'You should cut down on sugar.',
    example_vi: 'Bạn nên cắt giảm đường.',
    exam_context: 'Nguồn: KS T1/2026',
    sentence: 'The doctor advised him to ______ fatty food.',
    options: ['cut down on', 'come across', 'rule out', 'stand out'],
    correct_index: 0,
    sentence_explanation: 'Bác sĩ khuyên anh ấy cắt giảm đồ ăn nhiều chất béo.'
  },
  {
    phrase: 'set in',
    type: 'phrasal_verb',
    meaning_vi: 'Bắt đầu (và có vẻ tiếp tục, thường là xấu)',
    cambridge_def: 'to start and seem likely to continue (usually of something unpleasant)',
    example_en: 'Winter has set in early this year.',
    example_vi: 'Mùa đông đến sớm năm nay.',
    exam_context: 'Nguồn: KS T1/2026',
    sentence: 'A feeling of despair ______ after the team lost the final match.',
    options: ['set in', 'gave out', 'cut down on', 'stood out'],
    correct_index: 0,
    sentence_explanation: 'Cảm giác tuyệt vọng bắt đầu ập đến sau khi đội thua trận chung kết.'
  },
  {
    phrase: 'stand out',
    type: 'phrasal_verb',
    meaning_vi: 'Nổi bật, xuất sắc hơn',
    cambridge_def: 'to be much better or more important than others',
    example_en: 'Her performance stood out from the rest.',
    example_vi: 'Phần trình diễn của cô ấy nổi bật hơn so với phần còn lại.',
    exam_context: 'Nguồn: KS T1/2026',
    sentence: 'Among all the candidates, she clearly ______ as the most qualified.',
    options: ['stood out', 'set in', 'gave out', 'came across'],
    correct_index: 0,
    sentence_explanation: 'Trong tất cả ứng viên, cô ấy rõ ràng nổi bật là người đủ tiêu chuẩn nhất.'
  },
  {
    phrase: 'carry out',
    type: 'phrasal_verb',
    meaning_vi: 'Thực hiện, tiến hành',
    cambridge_def: 'to do or complete something, especially a task',
    example_en: 'The scientists carried out a series of experiments.',
    example_vi: 'Các nhà khoa học đã tiến hành một loạt thí nghiệm.',
    exam_context: 'Nguồn: VIP90 Đề 12',
    sentence: 'The government plans to ______ a nationwide survey on education.',
    options: ['carry out', 'pick out', 'put on', 'point out'],
    correct_index: 0,
    sentence_explanation: 'Chính phủ dự định thực hiện một cuộc khảo sát toàn quốc về giáo dục.'
  },
  {
    phrase: 'pick out',
    type: 'phrasal_verb',
    meaning_vi: 'Chọn ra, lựa chọn',
    cambridge_def: 'to choose someone or something from a group',
    example_en: 'She picked out a dress for the party.',
    example_vi: 'Cô ấy chọn ra một chiếc váy cho bữa tiệc.',
    exam_context: 'Nguồn: VIP90 Đề 12',
    sentence: 'Can you ______ the best option from these three designs?',
    options: ['pick out', 'carry out', 'put on', 'point out'],
    correct_index: 0,
    sentence_explanation: 'Bạn có thể chọn ra phương án tốt nhất từ ba thiết kế này không?'
  },
  {
    phrase: 'put on',
    type: 'phrasal_verb',
    meaning_vi: 'Tổ chức, trình diễn (sự kiện)',
    cambridge_def: 'to organize or provide an event or performance',
    example_en: 'The school is putting on a play this weekend.',
    example_vi: 'Trường tổ chức một vở kịch cuối tuần này.',
    exam_context: 'Nguồn: VIP90 Đề 12',
    sentence: 'The community center is ______ a free concert next Saturday.',
    options: ['putting on', 'carrying out', 'picking out', 'pointing out'],
    correct_index: 0,
    sentence_explanation: 'Trung tâm cộng đồng sẽ tổ chức một buổi hòa nhạc miễn phí thứ Bảy tới.'
  },
  {
    phrase: 'point out',
    type: 'phrasal_verb',
    meaning_vi: 'Chỉ ra, lưu ý',
    cambridge_def: 'to tell someone about some information; to show someone something',
    example_en: 'She pointed out the errors in the report.',
    example_vi: 'Cô ấy chỉ ra các lỗi trong báo cáo.',
    exam_context: 'Nguồn: VIP90 Đề 15',
    sentence: 'The teacher ______ that the assignment was due on Friday.',
    options: ['pointed out', 'carried out', 'picked out', 'put on'],
    correct_index: 0,
    sentence_explanation: 'Giáo viên chỉ ra rằng bài tập phải nộp vào thứ Sáu.'
  },
  {
    phrase: 'cut off (from)',
    type: 'phrasal_verb',
    meaning_vi: 'Cô lập, cắt đứt liên lạc',
    cambridge_def: 'to separate someone from people or things they usually have contact with',
    example_en: 'The village was cut off from the outside world.',
    example_vi: 'Ngôi làng bị cô lập khỏi thế giới bên ngoài.',
    exam_context: 'Nguồn: VIP90 Đề 15',
    sentence: 'The flood ______ several villages ______ the main road.',
    options: ['cut…off from', 'passed…on to', 'pointed…out to', 'came…from'],
    correct_index: 0,
    sentence_explanation: 'Lũ lụt đã cô lập nhiều ngôi làng khỏi con đường chính.'
  },
  {
    phrase: 'pass on',
    type: 'phrasal_verb',
    meaning_vi: 'Truyền đạt, chuyển tiếp',
    cambridge_def: 'to give information, goods, or a disease to another person',
    example_en: 'Could you pass on the message to her?',
    example_vi: 'Bạn có thể chuyển tin nhắn cho cô ấy không?',
    exam_context: 'Nguồn: VIP90 Đề 15',
    sentence: 'Please ______ this information to all team members.',
    options: ['pass on', 'cut off', 'point out', 'carry out'],
    correct_index: 0,
    sentence_explanation: 'Vui lòng chuyển tiếp thông tin này cho tất cả thành viên nhóm.'
  },

  // ===== COLLOCATIONS =====
  {
    phrase: 'reduce traffic congestion',
    type: 'collocation',
    meaning_vi: 'Giảm ùn tắc giao thông',
    cambridge_def: 'to lessen the problem of too many vehicles on roads',
    example_en: 'Building more bike lanes can reduce traffic congestion.',
    example_vi: 'Xây thêm làn xe đạp có thể giảm ùn tắc giao thông.',
    exam_context: 'Nguồn: Đề 25',
    sentence: 'The new metro system aims to ______ in the city center.',
    options: ['reduce traffic congestion', 'promote greener mobility', 'improve air quality', 'build a distinct brand'],
    correct_index: 0,
    sentence_explanation: 'Hệ thống tàu điện ngầm mới nhằm giảm ùn tắc giao thông ở trung tâm thành phố.'
  },
  {
    phrase: 'engage in',
    type: 'collocation',
    meaning_vi: 'Tham gia vào, dấn thân vào',
    cambridge_def: 'to take part in or become involved in something',
    example_en: 'Students should engage in extracurricular activities.',
    example_vi: 'Học sinh nên tham gia vào các hoạt động ngoại khóa.',
    exam_context: 'Nguồn: Đề 25 / Đề 03',
    sentence: 'Young people are encouraged to ______ community service.',
    options: ['engage in', 'align with', 'pose a problem', 'erode trust'],
    correct_index: 0,
    sentence_explanation: 'Thanh niên được khuyến khích tham gia vào hoạt động phục vụ cộng đồng.'
  },
  {
    phrase: 'make a significant difference',
    type: 'collocation',
    meaning_vi: 'Tạo ra sự khác biệt đáng kể',
    cambridge_def: 'to have an important effect on a situation',
    example_en: 'Your donation can make a significant difference.',
    example_vi: 'Khoản đóng góp của bạn có thể tạo ra sự khác biệt đáng kể.',
    exam_context: 'Nguồn: Đề 03',
    sentence: 'Even small actions can ______ to the environment.',
    options: ['make a significant difference', 'pose a problem', 'erode public trust', 'drive traffic'],
    correct_index: 0,
    sentence_explanation: 'Ngay cả những hành động nhỏ cũng có thể tạo ra sự khác biệt đáng kể cho môi trường.'
  },
  {
    phrase: 'gain knowledge',
    type: 'collocation',
    meaning_vi: 'Thu nhận kiến thức',
    cambridge_def: 'to obtain information and understanding',
    example_en: 'Reading helps you gain knowledge about the world.',
    example_vi: 'Đọc sách giúp bạn thu nhận kiến thức về thế giới.',
    exam_context: 'Nguồn: VIP90 Đề 12',
    sentence: 'Students ______ not only from textbooks but also from real-life experiences.',
    options: ['gain knowledge', 'develop reading habits', 'pose a problem', 'meet standards'],
    correct_index: 0,
    sentence_explanation: 'Học sinh thu nhận kiến thức không chỉ từ sách giáo khoa mà còn từ trải nghiệm thực tế.'
  },
  {
    phrase: 'pose a problem',
    type: 'collocation',
    meaning_vi: 'Đặt ra/gây ra vấn đề',
    cambridge_def: 'to create or represent a difficulty',
    example_en: 'The lack of funding poses a serious problem.',
    example_vi: 'Thiếu nguồn tài trợ gây ra vấn đề nghiêm trọng.',
    exam_context: 'Nguồn: Đề 03',
    sentence: 'Climate change ______ for coastal communities worldwide.',
    options: ['poses a problem', 'gains knowledge', 'meets standards', 'drives traffic'],
    correct_index: 0,
    sentence_explanation: 'Biến đổi khí hậu gây ra vấn đề cho các cộng đồng ven biển trên toàn thế giới.'
  },
  {
    phrase: 'meet international standards',
    type: 'collocation',
    meaning_vi: 'Đạt tiêu chuẩn quốc tế',
    cambridge_def: 'to satisfy the required levels set internationally',
    example_en: 'All products must meet international standards.',
    example_vi: 'Tất cả sản phẩm phải đạt tiêu chuẩn quốc tế.',
    exam_context: 'Nguồn: KS T1/2026',
    sentence: 'The new hospital was built to ______.',
    options: ['meet international standards', 'erode public trust', 'gain knowledge', 'pose a problem'],
    correct_index: 0,
    sentence_explanation: 'Bệnh viện mới được xây dựng để đạt tiêu chuẩn quốc tế.'
  },
  {
    phrase: 'erode public trust',
    type: 'collocation',
    meaning_vi: 'Làm xói mòn lòng tin công chúng',
    cambridge_def: 'to gradually weaken the confidence people have in institutions',
    example_en: 'Corruption erodes public trust in the government.',
    example_vi: 'Tham nhũng làm xói mòn lòng tin công chúng vào chính phủ.',
    exam_context: 'Nguồn: Đề 03',
    sentence: 'Fake news can ______ in the media.',
    options: ['erode public trust', 'meet standards', 'gain knowledge', 'make a difference'],
    correct_index: 0,
    sentence_explanation: 'Tin giả có thể làm xói mòn lòng tin công chúng vào truyền thông.'
  },
  {
    phrase: 'sleep deprivation',
    type: 'collocation',
    meaning_vi: 'Thiếu ngủ, mất ngủ',
    cambridge_def: 'the state of not getting enough sleep',
    example_en: 'Sleep deprivation can affect your health.',
    example_vi: 'Thiếu ngủ có thể ảnh hưởng đến sức khỏe của bạn.',
    exam_context: 'Nguồn: VIP90 Đề 12',
    sentence: '______ is a common problem among university students during exam season.',
    options: ['Sleep deprivation', 'Cognitive performance', 'Food security', 'Crop failure'],
    correct_index: 0,
    sentence_explanation: 'Thiếu ngủ là vấn đề phổ biến ở sinh viên đại học trong mùa thi.'
  },
  {
    phrase: 'food security',
    type: 'collocation',
    meaning_vi: 'An ninh lương thực',
    cambridge_def: 'the state of having reliable access to enough food',
    example_en: 'Climate change threatens global food security.',
    example_vi: 'Biến đổi khí hậu đe dọa an ninh lương thực toàn cầu.',
    exam_context: 'Nguồn: VIP90 Đề 15',
    sentence: 'Drought and flooding pose serious threats to ______ in developing countries.',
    options: ['food security', 'sleep deprivation', 'crop failure', 'cognitive performance'],
    correct_index: 0,
    sentence_explanation: 'Hạn hán và lũ lụt gây ra mối đe dọa nghiêm trọng cho an ninh lương thực ở các nước đang phát triển.'
  },
  {
    phrase: 'in short supply',
    type: 'collocation',
    meaning_vi: 'Khan hiếm, thiếu hụt',
    cambridge_def: 'available only in small amounts; not enough of something',
    example_en: 'Clean water is in short supply in many regions.',
    example_vi: 'Nước sạch khan hiếm ở nhiều khu vực.',
    exam_context: 'Nguồn: VIP90 Đề 15',
    sentence: 'During the pandemic, face masks were ______.',
    options: ['in short supply', 'in line with', 'in favour of', 'in advance'],
    correct_index: 0,
    sentence_explanation: 'Trong đại dịch, khẩu trang bị khan hiếm.'
  },

  // ===== FIXED PHRASES =====
  {
    phrase: 'in line with',
    type: 'fixed_phrase',
    meaning_vi: 'Phù hợp với, theo đúng',
    cambridge_def: 'in agreement with; following',
    example_en: 'The decision is in line with company policy.',
    example_vi: 'Quyết định phù hợp với chính sách công ty.',
    exam_context: 'Nguồn: Đề 03',
    sentence: 'All procedures must be ______ safety regulations.',
    options: ['in line with', 'in favour of', 'in response to', 'in conjunction with'],
    correct_index: 0,
    sentence_explanation: 'Tất cả quy trình phải phù hợp với quy định an toàn.'
  },
  {
    phrase: 'in favour of',
    type: 'fixed_phrase',
    meaning_vi: 'Ủng hộ, tán thành',
    cambridge_def: 'in support of; preferring something over something else',
    example_en: 'Are you in favour of the new policy?',
    example_vi: 'Bạn có ủng hộ chính sách mới không?',
    exam_context: 'Nguồn: KS T1/2026',
    sentence: 'The majority of voters are ______ stricter environmental laws.',
    options: ['in favour of', 'in line with', 'in response to', 'in terms of'],
    correct_index: 0,
    sentence_explanation: 'Đa số cử tri ủng hộ các luật môi trường nghiêm ngặt hơn.'
  },
  {
    phrase: 'in response to',
    type: 'fixed_phrase',
    meaning_vi: 'Để đáp lại, phản hồi lại',
    cambridge_def: 'as a reaction to something',
    example_en: 'The company changed its policy in response to customer complaints.',
    example_vi: 'Công ty thay đổi chính sách để đáp lại khiếu nại của khách hàng.',
    exam_context: 'Nguồn: KS T1/2026 / VIP90 Đề 12',
    sentence: 'The government introduced new measures ______ the rising crime rate.',
    options: ['in response to', 'in favour of', 'in line with', 'in conjunction with'],
    correct_index: 0,
    sentence_explanation: 'Chính phủ đưa ra các biện pháp mới để đáp lại tỷ lệ tội phạm gia tăng.'
  },
  {
    phrase: 'in conjunction with',
    type: 'fixed_phrase',
    meaning_vi: 'Kết hợp với, cùng với',
    cambridge_def: 'together with; combined with',
    example_en: 'The event was organized in conjunction with the local council.',
    example_vi: 'Sự kiện được tổ chức kết hợp với hội đồng địa phương.',
    exam_context: 'Nguồn: VIP90 Đề 15',
    sentence: 'The museum hosted the exhibition ______ a local art school.',
    options: ['in conjunction with', 'in response to', 'in favour of', 'in terms of'],
    correct_index: 0,
    sentence_explanation: 'Bảo tàng tổ chức triển lãm kết hợp với một trường nghệ thuật địa phương.'
  },
  {
    phrase: 'as a result',
    type: 'fixed_phrase',
    meaning_vi: 'Kết quả là, do đó',
    cambridge_def: 'because of something that happened before; consequently',
    example_en: 'He didn\'t study. As a result, he failed the exam.',
    example_vi: 'Anh ấy không học. Kết quả là, anh ấy trượt bài thi.',
    exam_context: 'Nguồn: Đề 25 / KS T1/2026',
    sentence: 'The company cut costs. ______, many employees lost their jobs.',
    options: ['As a result', 'At first', 'Above all', 'As a whole'],
    correct_index: 0,
    sentence_explanation: 'Công ty cắt giảm chi phí. Kết quả là, nhiều nhân viên mất việc.'
  },
  {
    phrase: 'above all',
    type: 'fixed_phrase',
    meaning_vi: 'Trên hết, quan trọng nhất',
    cambridge_def: 'most importantly; used to emphasize the most important point',
    example_en: 'Above all, we must protect our children.',
    example_vi: 'Trên hết, chúng ta phải bảo vệ trẻ em.',
    exam_context: 'Nguồn: VIP90 Đề 15',
    sentence: '______, students should focus on understanding, not just memorizing.',
    options: ['Above all', 'As a result', 'At first', 'Over time'],
    correct_index: 0,
    sentence_explanation: 'Trên hết, học sinh nên tập trung vào việc hiểu, chứ không chỉ ghi nhớ.'
  },
  {
    phrase: 'in terms of',
    type: 'fixed_phrase',
    meaning_vi: 'Về mặt, xét theo khía cạnh',
    cambridge_def: 'used to describe which aspect of a subject you are discussing',
    example_en: 'In terms of quality, this product is the best.',
    example_vi: 'Về mặt chất lượng, sản phẩm này là tốt nhất.',
    exam_context: 'Nguồn: VIP90 Đề 15',
    sentence: '______ revenue, the company had its best year ever.',
    options: ['In terms of', 'In favour of', 'In line with', 'In response to'],
    correct_index: 0,
    sentence_explanation: 'Về mặt doanh thu, công ty có năm tốt nhất từ trước đến nay.'
  },
  {
    phrase: 'in advance',
    type: 'fixed_phrase',
    meaning_vi: 'Trước, sớm (trước khi sự kiện xảy ra)',
    cambridge_def: 'before a particular time or event',
    example_en: 'You should book tickets in advance.',
    example_vi: 'Bạn nên đặt vé trước.',
    exam_context: 'Nguồn: VIP90 Đề 12',
    sentence: 'Please let us know ______ if you cannot attend the meeting.',
    options: ['in advance', 'at first', 'over time', 'as a whole'],
    correct_index: 0,
    sentence_explanation: 'Vui lòng cho chúng tôi biết trước nếu bạn không thể tham dự cuộc họp.'
  },
  {
    phrase: 'over time',
    type: 'fixed_phrase',
    meaning_vi: 'Theo thời gian, dần dần',
    cambridge_def: 'gradually; as time passes',
    example_en: 'The situation has improved over time.',
    example_vi: 'Tình hình đã cải thiện theo thời gian.',
    exam_context: 'Nguồn: Đề 25 / KS T1/2026',
    sentence: 'Your English will improve ______ if you practise regularly.',
    options: ['over time', 'in advance', 'at first', 'above all'],
    correct_index: 0,
    sentence_explanation: 'Tiếng Anh của bạn sẽ cải thiện theo thời gian nếu bạn luyện tập đều đặn.'
  },

  // ===== PREPOSITIONAL PHRASES =====
  {
    phrase: 'in the absence of',
    type: 'prepositional_phrase',
    meaning_vi: 'Khi không có, trong trường hợp thiếu',
    cambridge_def: 'when something is not present or available',
    example_en: 'In the absence of evidence, the case was dropped.',
    example_vi: 'Khi không có bằng chứng, vụ án bị hủy bỏ.',
    exam_context: 'Nguồn: Đề 25',
    sentence: '______ clear guidelines, employees may make inconsistent decisions.',
    options: ['In the absence of', 'At the forefront of', 'With regard to', 'Apart from'],
    correct_index: 0,
    sentence_explanation: 'Khi không có hướng dẫn rõ ràng, nhân viên có thể đưa ra quyết định không nhất quán.'
  },
  {
    phrase: 'with regard to',
    type: 'prepositional_phrase',
    meaning_vi: 'Liên quan đến, về vấn đề',
    cambridge_def: 'concerning; on the subject of',
    example_en: 'I am writing with regard to your recent inquiry.',
    example_vi: 'Tôi viết thư liên quan đến yêu cầu gần đây của bạn.',
    exam_context: 'Nguồn: VIP90 Đề 15',
    sentence: '______ your application, we would like to invite you for an interview.',
    options: ['With regard to', 'Apart from', 'In the absence of', 'At the peak of'],
    correct_index: 0,
    sentence_explanation: 'Liên quan đến đơn ứng tuyển của bạn, chúng tôi muốn mời bạn phỏng vấn.'
  },
  {
    phrase: 'apart from',
    type: 'prepositional_phrase',
    meaning_vi: 'Ngoài ra, ngoại trừ',
    cambridge_def: 'except for; in addition to',
    example_en: 'Apart from the cost, the plan is excellent.',
    example_vi: 'Ngoài chi phí ra, kế hoạch rất tuyệt vời.',
    exam_context: 'Nguồn: VIP90 Đề 15',
    sentence: '______ English, she can also speak French and German.',
    options: ['Apart from', 'With regard to', 'In the absence of', 'At the forefront of'],
    correct_index: 0,
    sentence_explanation: 'Ngoài tiếng Anh, cô ấy còn có thể nói tiếng Pháp và tiếng Đức.'
  },
  {
    phrase: 'at the peak of',
    type: 'prepositional_phrase',
    meaning_vi: 'Ở đỉnh cao của, ở thời điểm cao nhất',
    cambridge_def: 'at the highest point or most intense moment of something',
    example_en: 'The singer was at the peak of her career.',
    example_vi: 'Ca sĩ đang ở đỉnh cao sự nghiệp.',
    exam_context: 'Nguồn: VIP90 Đề 15',
    sentence: '______ the crisis, hospitals were overwhelmed with patients.',
    options: ['At the peak of', 'In the absence of', 'Apart from', 'With regard to'],
    correct_index: 0,
    sentence_explanation: 'Ở đỉnh cao của cuộc khủng hoảng, các bệnh viện bị quá tải bệnh nhân.'
  }
];
