/**
 * Global Success 11 - Unit 1 Lesson 6 (Writing)
 * A Short Message
 * Full Slide Deck & Interactive Message Studio
 */

const LESSON6_SLIDES = [
  { id: 1, title: "GLOBAL SUCCESS 11", subtitle: "UNIT 1: A LONG AND HEALTHY LIFE", desc: "Living Long and Healthy: Key Habits for a Better Life", cat: "Cover", img: "assets/lesson6/image1.jpeg", reveal: "Lesson 6: Writing – A Short Message" },
  { id: 2, title: "Lesson 6 Outline", subtitle: "Writing Skills", desc: "• Warm-up: When did you last text a friend? Sentence ordering puzzle\n• Structural Anatomy: The 3 Core Parts of a Short Message (Greeting, Body, Closing)\n• Task 1: Put scrambled message parts in correct chronological order\n• Useful Language: Inviting, giving time/place, stating purpose, polite sign-offs\n• Task 2: Sentence expansion practice with given starters\n• Task 3: Write a short message replying to an invitation (Accept or Decline)\n• Task 4: Interactive Message Studio & Peer Review Checklist (NLS 3.1NC1a)\n• Consolidation & Homework", cat: "Agenda", img: "assets/lesson6/image2.png" },
  { id: 3, title: "WARM - UP", subtitle: "Texting in the Digital Era", desc: "How often do you communicate using short text messages, chat apps, or notes?", cat: "Warm-up", img: "assets/lesson6/image3.svg" },
  { id: 4, title: "Warm-up Discussion", subtitle: "Personal Communication Habits", desc: "Question 1: When was the last time you sent a short message?\nQuestion 2: What was the main purpose of that message?\n(e.g., asking for homework, inviting someone to play sports, saying happy birthday, confirming a meeting time)", cat: "Warm-up", img: "assets/lesson6/image4.png", reveal: "Short messages are concise, direct, and purposeful." },
  { id: 5, title: "Mini Game: Order the Sentences", subtitle: "Warm-up Puzzle", desc: "Put the scrambled lines into a coherent short message:\nA. Hope you can make it! Best, Nam\nB. Hi Linda,\nC. We are meeting at 6:30 AM at the city park.\nD. Do you want to join our cycling club this Saturday?", cat: "Warm-up", img: "assets/lesson6/image6.png", reveal: "👉 Correct Order: B ➔ D ➔ C ➔ A" },
  { id: 6, title: "THE 3 PARTS OF A SHORT MESSAGE", subtitle: "Structural Anatomy", desc: "A standard short message consists of 3 distinct sections:\n1. GREETING: Open with a friendly salutation (Hi Linda, / Dear Mark,)\n2. BODY:\n   • Reason / Purpose for writing (Do you fancy coming to... / I am writing to invite you...)\n   • Key Details (Time, exact location, what to bring)\n   • Request for confirmation (Please let me know by Friday)\n3. CLOSING: Courteous sign-off and sender's signature (Best, / See you soon, / Love,)", cat: "Structure", img: "assets/lesson6/image8.png" },
  { id: 7, title: "TASK 1: Analyze the Model Message", subtitle: "Model Text Breakdown", desc: "Read Nam's message to Linda:\n'Hi Linda,\nDo you want to join our cycling club this Saturday morning? We’re meeting at 6:30 a.m. at the park entrance. Cycling is a great way to stay fit and active on the weekend! Please let me know by Friday so I can arrange the bikes.\nHope you can make it!\nBest,\nNam'", cat: "Practice", img: "assets/lesson6/image10.png", reveal: "Notice how every sentence has a specific communicative purpose!" },
  { id: 8, title: "Useful Expressions: Inviting", subtitle: "Sentence Starters", desc: "Ways to invite someone to a health activity:\n• Would you like to join me for [activity]?\n• Do you want to come to [event]?\n• How about going for a run together this weekend?\n• Are you free to work out with us on Sunday?", cat: "Language", img: "assets/lesson6/image12.png" },
  { id: 9, title: "Useful Expressions: Giving Details", subtitle: "Logistical Information", desc: "Ways to state time, location, and requirements:\n• We are meeting at [time] at [location].\n• The class starts at [time], so please arrive 10 minutes early.\n• Don’t forget to bring your sports shoes and a water bottle.\n• The entrance fee is completely free!", cat: "Language", img: "assets/lesson6/image14.png" },
  { id: 10, title: "Useful Expressions: Requesting Reply", subtitle: "Call to Action", desc: "Encouraging a prompt response:\n• Please let me know if you can come by [date].\n• Drop me a message as soon as you can.\n• Hope you can join us!\n• Looking forward to seeing you there!", cat: "Language", img: "assets/lesson6/image16.jpeg" },
  { id: 11, title: "TASK 2: Write Single Sentences", subtitle: "Controlled Writing Practice", desc: "Write full sentences starting with the given words:\n1. Would you like to... [invite to a yoga workshop]\n2. We are planning to... [meet at the school gym on Sunday]\n3. Please let me know... [by Thursday evening]", cat: "Practice", img: "assets/lesson6/image18.png", reveal: "1. Would you like to come to a weekend yoga workshop with me?\n2. We are planning to meet at the school gym this Sunday at 8 AM.\n3. Please let me know if you can make it by Thursday evening." },
  { id: 12, title: "TASK 3: Reply to Linda's Invitation", subtitle: "Writing Prompt", desc: "Now write a short message replying to Nam's cycling invitation.\nYou can choose to either:\n• OPTION A: ACCEPT the invitation with enthusiasm.\n• OPTION B: DECLINE politely with a sensible health/schedule reason.", cat: "Production", img: "assets/lesson6/image20.png" },
  { id: 13, title: "Sample Reply: Acceptance", subtitle: "Model Option A", desc: "'Hi Nam,\nThanks for the invitation! I’d love to join your cycling club this Saturday. 6:30 a.m. at the park entrance sounds great. I’ll make sure to bring my helmet and water bottle.\nSee you on Saturday!\nBest,\nLinda'", cat: "Production", img: "assets/lesson6/image22.png", reveal: "Key elements: Gratitude ➔ Acceptance ➔ Reconfirm time/venue ➔ Cheerful sign-off." },
  { id: 14, title: "Sample Reply: Polite Refusal", subtitle: "Model Option B", desc: "'Hi Nam,\nThank you so much for inviting me to join the cycling club! I would really love to, but I have a doctor’s check-up scheduled for 7:00 a.m. this Saturday, so I won’t be able to make it.\nHave a wonderful ride, and let’s catch up next weekend!\nBest,\nLinda'", cat: "Production", img: "assets/lesson6/image24.png", reveal: "Key elements: Gratitude ➔ Polite 'no' + legitimate reason ➔ Warm wishes." },
  { id: 15, title: "TASK 4: Peer Review Checklist", subtitle: "Quality Criteria (NLS 3.1NC1a)", desc: "Exchange your message with your partner and check:\n[ ] 1. Greeting is appropriate and punctuated with a comma.\n[ ] 2. Response (acceptance or refusal) is stated clearly in the first 2 sentences.\n[ ] 3. Specific details or valid explanations are provided.\n[ ] 4. Polite, friendly tone throughout.\n[ ] 5. Closing sign-off and signature are correct.", cat: "Production", img: "assets/lesson6/image26.png", reveal: "Peer editing builds critical writing awareness and error recognition." },
  { id: 16, title: "CONSOLIDATION & WRAP-UP", subtitle: "Writing Summary", desc: "What have we mastered in Lesson 6?\n• The 3-part anatomy of a short message\n• Polite language for invitations, acceptances, and refusals\n• Peer review and self-editing strategies\n\nDigital Homework (NLS 3.1NC1a):\n- Type your finalized short message into your class forum or digital learning space.\n- Comment on two classmates' messages.", cat: "Wrap-up", img: "assets/lesson6/image28.png" },
  { id: 17, title: "THANK YOU!", subtitle: "Keep Communicating!", desc: "Clear, courteous writing connects people and inspires healthy habits! ✍️📬", cat: "Closing", img: "assets/lesson6/image29.png" }
];

window.Lesson6State = {
  currentSlide: 1,
  replyMode: 'accept',
  userDraft: ""
};
