/**
 * Global Success 11 - Unit 1 Lesson 5 (Listening)
 * Food and Health
 * Full Slide Deck & Interactive Meal Planner
 */

const LESSON5_SLIDES = [
  { id: 1, title: "GLOBAL SUCCESS 11", subtitle: "UNIT 1: A LONG AND HEALTHY LIFE", desc: "Living Long and Healthy: Key Habits for a Better Life", cat: "Cover", img: "assets/lesson5/image1.jpeg", reveal: "Lesson 5: Listening – Food and Health" },
  { id: 2, title: "Lesson 5 Outline", subtitle: "Listening Comprehension", desc: "• Warm-up: 'Let’s Talk About What We Eat' Brainstorming\n• Food Sorting: Healthy vs Unhealthy nutritional choices\n• Pre-teach Vocabulary: cut down on, acne, skincare, whole grains, processed food\n• Pre-listening: Predicting teen nutritional needs\n• While-listening: TV Chat Show 'Teen Life' with Dr. Oliver & Nutritionist\n• Task 2: Identify main topic of the TV show\n• Task 3: Identify foods recommended by the nutritionist\n• Task 4: Complete sentences with ONE word from the audio\n• Post-listening / Production: 1-Day Balanced Meal Planner (NLS 1.1NC1a)\n• Consolidation & Homework", cat: "Agenda", img: "assets/lesson5/image2.png" },
  { id: 3, title: "WARM - UP", subtitle: "Let's Talk About Food!", desc: "What did you eat for breakfast this morning? Was it nutritious?", cat: "Warm-up", img: "assets/lesson5/image4.png" },
  { id: 4, title: "Brainstorming Challenge", subtitle: "Healthy vs Unhealthy Foods", desc: "Can you name 4 healthy foods and 4 unhealthy foods you frequently see in your school or neighborhood?\n• Healthy: Apples, steamed fish, broccoli, oats, eggs, nuts...\n• Unhealthy: Deep-fried chips, sugary donuts, carbonated soda, instant noodles...", cat: "Warm-up", img: "assets/lesson5/image6.png", reveal: "Focus on unprocessed, whole foods vs heavily refined, sugary items." },
  { id: 5, title: "Healthy or Unhealthy?", subtitle: "Food Sorting Activity", desc: "Look at the foods on screen:\n1. Fresh salmon & avocado ➔ HEALTHY (rich in Omega-3 & unsaturated fats)\n2. Fizzy sugary soft drink ➔ UNHEALTHY (high glycemic index, causes dental cavities)\n3. Mixed leafy green salad ➔ HEALTHY (loaded with micronutrients & fiber)\n4. Double cheeseburger with fries ➔ UNHEALTHY (saturated fats, high sodium)", cat: "Warm-up", img: "assets/lesson5/image8.png", reveal: "Balance is key: occasional treats are fine, but daily foundation must be wholesome." },
  { id: 6, title: "Why Do Teenagers Need Healthy Food?", subtitle: "Nutritional Science", desc: "During adolescence, the human body undergoes rapid physical and neurological development.\n• Muscle & Bone Density: Requires calcium, vitamin D, and lean protein.\n• Cognitive Focus & Memory: Brain cells rely on omega-3 fatty acids and steady glucose from whole grains.\n• Hormonal Balance & Clear Skin: High-sugar diets cause insulin spikes, worsening teen acne.", cat: "Warm-up", img: "assets/lesson5/image10.png", reveal: "Good nutrition directly translates to higher test scores and stable emotional moods." },
  { id: 7, title: "Pre-listening Vocabulary", subtitle: "Essential Terms for Audio", desc: "1. cut down on /kʌt daʊn ɒn/ (phr v): cắt giảm bớt tiêu thụ\n2. acne /ˈækni/ (n): mụn trứng cá\n3. skincare /ˈskɪnkeə(r)/ (n): chăm sóc da\n4. whole grains /həʊl ɡreɪnz/ (n): ngũ cốc nguyên cám/nguyên hạt\n5. processed food /ˈprəʊsest fuːd/ (n): thực phẩm chế biến công nghiệp", cat: "Vocabulary", img: "assets/lesson5/image12.png" },
  { id: 8, title: "Vocabulary Check: Acne", subtitle: "Skin Health Connection", desc: "A skin condition common among adolescents characterized by red pimples on face and neck.\nExample: Cutting down on greasy snacks significantly reduced his acne.", cat: "Vocabulary", img: "assets/lesson5/image14.png", reveal: "acne (n) /'ækni/" },
  { id: 9, title: "Vocabulary Check: Cut Down On", subtitle: "Habit Adjustment", desc: "To reduce the amount or number of something you eat, drink, or use.\nExample: The doctor advised him to cut down on sugary bubble tea.", cat: "Vocabulary", img: "assets/lesson5/image16.png", reveal: "cut down on (phr v)" },
  { id: 10, title: "TV CHAT SHOW: TEEN LIFE", subtitle: "Listening Context", desc: "You will listen to an episode of 'Teen Life', a popular youth talk show discussing health and nutrition.", cat: "Listening", img: "assets/lesson5/image18.png" },
  { id: 11, title: "Listening Audio Transcript", subtitle: "Teen Life Broadcast", desc: "TV host: Good evening! I’m Oliver and you’re watching 'Teen Life', where we answer questions from young people. This week we have received a lot of health questions from teenagers asking about diet, skin, and fitness. Today, we have Dr. Mary with us to share practical nutrition advice for teenagers.\n\nDr. Mary: Hello Oliver! It is a pleasure to be here. Many teens ask why they feel sluggish during afternoon classes or why they suffer from skin breakouts. The main reason is often their daily diet. When teens eat too many processed snacks and drink sugary sodas, their blood sugar spikes and crashes, leaving them tired.\n\nHost: So what should teenagers eat instead?\n\nDr. Mary: First, replace white bread and sugary cereals with whole grains like oats and brown rice. Second, make sure to eat plenty of fresh vegetables and fruits every day. Third, eat lean protein such as fish, eggs, and tofu to support rapid bone and muscle growth. Finally, drink plenty of water and avoid energy drinks!", cat: "Listening", img: "assets/lesson5/image20.png" },
  { id: 12, title: "TASK 2: Topic of the Show", subtitle: "Gist Comprehension", desc: "Listen to the TV chat show. Circle the topic of the show:\nA. Fast food in schools\nB. Healthy eating for teenagers\nC. How to become a fitness trainer", cat: "Practice", img: "assets/lesson5/image22.png", reveal: "👉 Correct: B. Healthy eating for teenagers (The doctor provides diet advice tailored to teen growth and energy)" },
  { id: 13, title: "TASK 3: Recommended Foods", subtitle: "Selective Listening", desc: "Which foods does Dr. Mary recommend in the talk?\n[ ] 1. Fresh vegetables\n[ ] 2. Sugary sodas & energy drinks\n[ ] 3. Fish and lean protein\n[ ] 4. Deep-fried chips\n[ ] 5. Whole grains (oats, brown rice)\n[ ] 6. Fresh fruits\n[ ] 7. Plenty of water", cat: "Practice", img: "assets/lesson5/image24.png", reveal: "Recommended: 1, 3, 5, 6, 7 (Avoided: 2, 4)" },
  { id: 14, title: "TASK 4: Sentence Completion", subtitle: "Detailed Listening (ONE word each)", desc: "Complete each sentence with ONE word from the recording:\n1. Eating too much sugar and fast food can cause tiredness and _______ breakouts.\n2. Teenagers need _______ to support rapid muscle and bone growth.\n3. Whole grains release energy slowly, preventing afternoon _______.\n4. Drinking plenty of _______ keeps cells hydrated and clears the skin.", cat: "Practice", img: "assets/lesson5/image26.png", reveal: "1: acne (or skin) | 2: protein | 3: crashes (or fatigue) | 4: water" },
  { id: 15, title: "Post-listening: Production", subtitle: "1-Day Healthy Meal Planner", desc: "Work in groups. Design a realistic, delicious 1-day meal plan for an active 11th-grade student:\n• Breakfast: Energy & Brain focus\n• Lunch: Balanced macronutrients\n• Healthy Snack: Sustained endurance\n• Dinner: Light, restorative nutrition", cat: "Production", img: "assets/lesson5/image28.png", reveal: "Sample: Oatmeal + banana (Breakfast), Brown rice + grilled chicken + greens (Lunch), Greek yogurt + nuts (Snack), Steamed fish + pumpkin soup (Dinner)." },
  { id: 16, title: "Digital Research Task (NLS 1.1NC1a)", subtitle: "Nutritional Fact Checking", desc: "Use your smartphones or computers to look up the nutritional values of popular Vietnamese dishes:\n• Phở bò: ~450 kcal, high protein, sodium caution.\n• Bánh mì trứng: ~380 kcal, balanced carb & protein.\n• Gỏi cuốn (Fresh spring rolls): ~120 kcal per roll, very low fat, high fiber.", cat: "Production", img: "assets/lesson5/image30.png", reveal: "Choosing fresh herbs and reducing dipping sauce sodium improves nutritional profile." },
  { id: 17, title: "CONSOLIDATION & WRAP-UP", subtitle: "Lesson Takeaways", desc: "What have we achieved today?\n• Identified the connection between nutrition, acne, and energy\n• Practiced listening for main ideas and specific single-word details\n• Created a balanced 1-day teen meal plan\n\nHomework:\n- Record your personal 1-day food diary and evaluate its nutritional score.\n- Prepare for Lesson 6: Writing a Short Message.", cat: "Wrap-up", img: "assets/lesson5/image32.png" },
  { id: 18, title: "THANK YOU!", subtitle: "Eat Well, Live Well!", desc: "Feed your body with quality nutrition every single day! 🥑🥗", cat: "Closing", img: "assets/lesson5/image34.png" }
];

window.Lesson5State = {
  currentSlide: 1,
  selectedFoods: [],
  plannerMeals: {
    breakfast: "",
    lunch: "",
    snack: "",
    dinner: ""
  }
};
