/**
 * Global Success 11 - Unit 1 Lesson 3 (Reading)
 * How to Live a Long and Healthy Life
 * Complete Slide Deck & Interactive Reading Studio
 */

const LESSON3_SLIDES = [
  { id: 1, title: "GLOBAL SUCCESS 11", subtitle: "UNIT 1: A LONG AND HEALTHY LIFE", desc: "Living Long and Healthy: Key Habits for a Better Life", cat: "Cover", img: "assets/lesson3/image1.jpeg", reveal: "Lesson 3: Reading – How to Live a Long and Healthy Life" },
  { id: 2, title: "Lesson 3 Outline", subtitle: "Reading Comprehension", desc: "• Warm-up: Fresh Juice Review Minigame (10 Questions)\n• Lead-in: Healthy vs Unhealthy Habits in Photos\n• Pre-teach Vocabulary: life expectancy, nutrient, ingredient, repetitive, give off\n• Task 1: Photo Discussion\n• Task 2: Crossword Puzzle Challenge\n• Task 3: Matching Headings (Eat better, Move more, Sleep well)\n• Task 4: Complete the Diagrams\n• Task 5: Discussion & Extension\n• Consolidation & Homework", cat: "Agenda", img: "assets/lesson3/image2.png" },
  { id: 3, title: "WARM - UP", subtitle: "Fresh Juice Game", desc: "Let's review grammar and vocabulary from previous lessons to make fresh healthy fruit juice!", cat: "Warm-up", img: "assets/lesson3/image4.png" },
  { id: 4, title: "FRESH JUICE MINIGAME", subtitle: "Game Rules", desc: "Choose any number to display the corresponding question.\nAnswer correctly to blend fresh fruits into the juice maker!", cat: "Warm-up", img: "assets/lesson3/image6.png" },
  { id: 5, title: "Fresh Juice Question 1", subtitle: "Tense Check", desc: "He _______ (see) the doctor yesterday because he had a headache.\nA. is seeing | B. has seen | C. saw", cat: "Warm-up", img: "assets/lesson3/image7.png", reveal: "👉 Correct: C. saw (Dấu hiệu: yesterday - Past Simple)" },
  { id: 6, title: "Fresh Juice Question 2", subtitle: "Tense Check", desc: "Our fitness level _______ (improve) a lot in the last few months.\nA. has improved | B. improves | C. improved", cat: "Warm-up", img: "assets/lesson3/image9.png", reveal: "👉 Correct: A. has improved (Dấu hiệu: in the last few months - Present Perfect)" },
  { id: 7, title: "Fresh Juice Question 3", subtitle: "Vocabulary Check", desc: "To stay healthy, it is important to eat a ________ diet that includes fruits, vegetables, and proteins.\nA. fit | B. balanced | C. work out", cat: "Warm-up", img: "assets/lesson3/image11.png", reveal: "👉 Correct: B. balanced (a balanced diet = chế độ ăn uống cân bằng)" },
  { id: 8, title: "Fresh Juice Question 4", subtitle: "Tense Check", desc: "She _______ (not eat) junk food since she started her healthy lifestyle.\nA. didn’t eat | B. isn’t eating | C. hasn’t eaten", cat: "Warm-up", img: "assets/lesson3/image13.png", reveal: "👉 Correct: C. hasn’t eaten (Dấu hiệu: since + mệnh đề quá khứ)" },
  { id: 9, title: "Fresh Juice Question 5", subtitle: "Collocation Check", desc: "Bananas are _______ vitamins, which is good for your heart.\nA. full of | B. diet | C. fit", cat: "Warm-up", img: "assets/lesson3/image15.png", reveal: "👉 Correct: A. full of (full of vitamins = giàu vitamin)" },
  { id: 10, title: "Fresh Juice Question 6", subtitle: "Tense Check", desc: "I _______ (do) yoga for 3 years and I feel much healthier now.\nA. do | B. have done | C. did", cat: "Warm-up", img: "assets/lesson3/image17.png", reveal: "👉 Correct: B. have done (Dấu hiệu: for 3 years - Present Perfect)" },
  { id: 11, title: "Fresh Juice Question 7", subtitle: "Vocabulary Check", desc: "She works out every morning because she wants to be _______ and strong.\nA. work out | B. balanced | C. fit", cat: "Warm-up", img: "assets/lesson3/image19.png", reveal: "👉 Correct: C. fit (fit and strong = thon gọn và khỏe khoắn)" },
  { id: 12, title: "Fresh Juice Question 8", subtitle: "Tense Check", desc: "I _______ (feel) tired yesterday after the long hike.\nA. felt | B. feel | C. have felt", cat: "Warm-up", img: "assets/lesson3/image21.png", reveal: "👉 Correct: A. felt (Dấu hiệu: yesterday - Past Simple)" },
  { id: 13, title: "Fresh Juice Question 9", subtitle: "Vocabulary Check", desc: "It is helpful to _______ regularly to improve your overall health and strength.\nA. diet | B. work out | C. fit", cat: "Warm-up", img: "assets/lesson3/image23.png", reveal: "👉 Correct: B. work out (tập luyện thể thao đều đặn)" },
  { id: 14, title: "Fresh Juice Question 10", subtitle: "Tense Check", desc: "She _______ (have) a cold last week, but now she feels better.\nA. has | B. is having | C. had", cat: "Warm-up", img: "assets/lesson3/image25.png", reveal: "👉 Correct: C. had (Dấu hiệu: last week - Past Simple)" },
  { id: 15, title: "READING PASSAGE", subtitle: "How to Live a Long and Healthy Life", desc: "Unit 1 Reading explores the scientific lifestyle habits that promote longevity and vital health.", cat: "Reading", img: "assets/lesson3/image27.png" },
  { id: 16, title: "Task 1: Habits in Photos", subtitle: "Healthy vs Unhealthy", desc: "Look at the photos in the book:\nPhoto 1: Fresh salad and water (Healthy)\nPhoto 2: Late night gaming with screen glare (Unhealthy)\nPhoto 3: Outdoor jogging in nature (Healthy)\nPhoto 4: Eating fast food & drinking sugary soda (Unhealthy)", cat: "Practice", img: "assets/lesson3/image28.png", reveal: "Healthy: salad, drinking water, running outdoor | Unhealthy: late screens, fast food" },
  { id: 17, title: "Core Vocabulary Spotlight", subtitle: "5 Key Words for Reading", desc: "1. life expectancy /laɪf ɪkˈspektənsi/ (n): tuổi thọ dự tính\n2. nutrient /ˈnjuːtriənt/ (n): chất dinh dưỡng\n3. ingredient /ɪnˈɡriːdiənt/ (n): nguyên liệu, thành phần\n4. repetitive /rɪˈpetətɪv/ (adj): lặp đi lặp lại\n5. give off /ɡɪv ɒf/ (phr v): phát ra, tỏa ra (ánh sáng/khí)", cat: "Vocabulary", img: "assets/lesson3/image30.png" },
  { id: 18, title: "Vocabulary Check: Nutrient", subtitle: "Definition", desc: "A substance that plants or animals need in order to live and grow.\nExample: Vegetables are packed with vital nutrients for our immune system.", cat: "Vocabulary", img: "assets/lesson3/image33.png", reveal: "nutrient (n)" },
  { id: 19, title: "Vocabulary Check: Life Expectancy", subtitle: "Definition", desc: "The number of years that a person is likely to live.\nExample: Medical advancements have drastically boosted human life expectancy.", cat: "Vocabulary", img: "assets/lesson3/image34.png", reveal: "life expectancy (n)" },
  { id: 20, title: "Vocabulary Check: Repetitive", subtitle: "Definition", desc: "Doing or saying the same thing many times in a way that feels boring or mechanical.\nExample: Doing repetitive exercise without variety can feel tedious.", cat: "Vocabulary", img: "assets/lesson3/image35.png", reveal: "repetitive (adj)" },
  { id: 21, title: "Vocabulary Check: Ingredient", subtitle: "Definition", desc: "One of the things from which a food item or dish is made.\nExample: Always read food labels to inspect the healthy ingredients.", cat: "Vocabulary", img: "assets/lesson3/image36.png", reveal: "ingredient (n)" },
  { id: 22, title: "Vocabulary Check: Give off", subtitle: "Definition", desc: "To produce or emit something such as heat, light, or a smell.\nExample: Smartphones give off blue light that disrupts melatonin and sleep.", cat: "Vocabulary", img: "assets/lesson3/image37.png", reveal: "give off (phr v)" },
  { id: 23, title: "Reading Article: Part A", subtitle: "Eat Better", desc: "What kind of food should we eat to live longer?\n• Study food labels to choose nutrient-rich whole foods.\n• Avoid too much salt and refined sugar.\n• Add fresh fruits, leafy vegetables, and whole grains to your daily meals.\n• Drink at least 1.5 - 2 liters of water daily to maintain cellular hydration.", cat: "Reading", img: "assets/lesson3/image39.png" },
  { id: 24, title: "Reading Article: Part B", subtitle: "Move More", desc: "How does physical activity protect our bodies?\n• Engage in at least 30 minutes of moderate physical exercise daily.\n• Walking, cycling, swimming, and home workouts strengthen muscles and bones.\n• Prevent repetitive strain by mixing cardio with mobility and bodyweight exercises.\n• Physical movement triggers endorphins, reducing chronic stress and anxiety.", cat: "Reading", img: "assets/lesson3/image40.png" },
  { id: 25, title: "Reading Article: Part C", subtitle: "Sleep Well", desc: "Why is restful sleep non-negotiable for longevity?\n• Get 7 to 8 hours of restorative sleep every single night.\n• Electronic screens give off blue light that tricks the brain into staying awake.\n• Turn off phones and laptops at least 30-60 minutes before bedtime.\n• Keep the bedroom cool, dark, and quiet to encourage deep REM sleep.", cat: "Reading", img: "assets/lesson3/image41.png" },
  { id: 26, title: "Task 2: Crossword Puzzle", subtitle: "Vocabulary in Text", desc: "1. The number of years a person can live: LIFE EXPECTANCY\n2. A chemical or substance that provides nourishment: NUTRIENT\n3. A component of a food mixture: INGREDIENT\n4. Happening over and over again: REPETITIVE\n5. To emit light, sound, or gas: GIVE OFF", cat: "Practice", img: "assets/lesson3/image38.png", reveal: "1: life expectancy | 2: nutrient | 3: ingredient | 4: repetitive | 5: give off" },
  { id: 27, title: "Task 3: Match Headings", subtitle: "Structure of the Article", desc: "Match each section of the article with its main heading:\nSection A: Eat better\nSection B: Move more\nSection C: Sleep well", cat: "Practice", img: "assets/lesson3/image39.png", reveal: "Section A -> Eat better | Section B -> Move more | Section C -> Sleep well" },
  { id: 28, title: "Task 4: Complete the Diagrams", subtitle: "Key Advice from the Text", desc: "Complete each branch of the longevity diagram with NO MORE THAN TWO WORDS:\n• Food: Study food labels / Avoid salt & sugar / Add fresh fruits.\n• Exercise: At least 30 minutes / Mix different activities / Strengthen muscles.\n• Sleep: 7 to 8 hours / Turn off screens / Avoid blue light.", cat: "Practice", img: "assets/lesson3/image40.png", reveal: "1. food labels | 2. salt / sugar | 3. 30 minutes | 4. muscles | 5. 7 to 8 | 6. blue light" },
  { id: 29, title: "Task 5: Discussion & Extension", subtitle: "Personal Reflection", desc: "Work in pairs and discuss:\n1. Which of the 3 habits (eating, moving, sleeping) do you find easiest to follow?\n2. What is the biggest barrier preventing teenagers from sleeping 8 hours a night?\n3. What is one habit you will change starting today?", cat: "Practice", img: "assets/lesson3/image41.png", reveal: "Sample: Most teens struggle with sleep due to late homework and smartphone blue light." },
  { id: 30, title: "CONSOLIDATION & HOMEWORK", subtitle: "Wrap-up", desc: "What have we learnt today?\n• Core vocabulary related to nutrition, fitness, and sleep\n• Reading for gist and scanning for specific figures\n• 3 pillars of longevity: Nutrition, Physical Activity, Restful Sleep\n\nHomework:\n- Write a short summary (80-100 words) of the article.\n- Prepare for Lesson 4: Speaking.", cat: "Wrap-up", img: "assets/lesson3/image42.png" },
  { id: 31, title: "THANK YOU!", subtitle: "Great Reading Session!", desc: "Apply these 3 pillars every day for a vibrant, healthy life! 🥗🏃‍♂️💤", cat: "Closing", img: "assets/lesson3/image43.png" }
];

window.Lesson3State = {
  currentSlide: 1,
  juiceScore: 0,
  activeMode: 'presentation'
};
