/**
 * Global Success 11 - Unit 1 Lesson 7 (Communication and Culture / CLIL)
 * Everyday English: Offering Help & Biology: Bacteria and Viruses
 * Full Slide Deck & Interactive CLIL Studio
 */

const LESSON7_SLIDES = [
  { id: 1, title: "GLOBAL SUCCESS 11", subtitle: "UNIT 1: A LONG AND HEALTHY LIFE", desc: "Living Long and Healthy: Key Habits for a Better Life", cat: "Cover", img: "assets/lesson7/image1.jpeg", reveal: "Lesson 7: Communication and Culture / CLIL" },
  { id: 2, title: "Lesson 7 Outline", subtitle: "Functional English & CLIL Biology", desc: "• Warm-up: Unit 1 Grammar Review Quiz (Past Simple vs Present Perfect)\n• Everyday English: Offering Help and Responding to Offers\n• Dialogue Practice & Situational Role-play (p. 15)\n• CLIL (Biology): Bacteria and Viruses (p. 16)\n• Task 1: Complete Comparison Table (Living status, Size, Structure, Treatment)\n• Review Minigame: 10 Challenge Questions on Microorganisms\n• Task 2: Health Advisory Scenarios (Overusing Antibiotics & Vaccines)\n• Video & Case Study: COVID-19 Prevention & Public Health (NLS 4.3NC1a)\n• Consolidation & Homework", cat: "Agenda", img: "assets/lesson7/image2.png" },
  { id: 3, title: "WARM - UP", subtitle: "Grammar & Tense Review", desc: "Let's test our mastery of Past Simple and Present Perfect tenses before diving into today's lesson!", cat: "Warm-up", img: "assets/lesson7/image3.svg" },
  { id: 4, title: "Warm-up Question 1", subtitle: "Tense Check", desc: "We _______ (work out) regularly this year to improve our fitness.\nA. have worked out\nB. worked out\nC. are working out", cat: "Warm-up", img: "assets/lesson7/image4.png", reveal: "👉 Correct: A. have worked out (Dấu hiệu: this year - ongoing period)" },
  { id: 5, title: "Warm-up Question 2", subtitle: "Tense Check", desc: "I _______ (cut down on) sugary snacks last month to improve my health.\nA. have cut down on\nB. cut down on\nC. had cut down on", cat: "Warm-up", img: "assets/lesson7/image5.png", reveal: "👉 Correct: B. cut down on (Dấu hiệu: last month - Past Simple)" },
  { id: 6, title: "Warm-up Question 3", subtitle: "Sentence Scramble", desc: "They / try / new skincare products / recently.\nA. They tried new skincare products recently.\nB. They are trying new skincare products recently.\nC. They have tried new skincare products recently.", cat: "Warm-up", img: "assets/lesson7/image6.png", reveal: "👉 Correct: C. They have tried... (Dấu hiệu: recently - Present Perfect)" },
  { id: 7, title: "Warm-up Question 4", subtitle: "Tense Check", desc: "He _______ (star jump) 100 times yesterday morning.\nA. star jumped\nB. has star jumped\nC. star jumps", cat: "Warm-up", img: "assets/lesson7/image7.png", reveal: "👉 Correct: A. star jumped (Dấu hiệu: yesterday morning - Past Simple)" },
  { id: 8, title: "Warm-up Question 5", subtitle: "Tense Check", desc: "She _______ (not / squat) since last week because of a leg injury.\nA. didn't squat\nB. hasn’t squatted\nC. doesn't squat", cat: "Warm-up", img: "assets/lesson7/image8.png", reveal: "👉 Correct: B. hasn't squatted (Dấu hiệu: since last week - Present Perfect)" },
  { id: 9, title: "EVERYDAY ENGLISH", subtitle: "Offering Help & Responding", desc: "In daily life, offering assistance politely and responding graciously builds strong social connections.", cat: "Everyday English", img: "assets/lesson7/image10.png" },
  { id: 10, title: "Model Dialogue: Offering Help", subtitle: "Listening & Reading (p. 15)", desc: "Tom: You look exhausted from that workout! Can I give you a hand with carrying the gym mats?\nMai: Yes, please. That's very kind of you!\nTom: Would you like me to get you some cold water from the dispenser?\nMai: No, thank you. I've got my own water bottle right here, but thanks for asking!", cat: "Everyday English", img: "assets/lesson7/image12.png", reveal: "Notice Tom's helpfulness and Mai's polite responses (accepting vs declining)." },
  { id: 11, title: "Structures for Offering Help", subtitle: "Functional Phrases", desc: "Formal & Informal ways to offer assistance:\n• Can I give you a hand with [noun / V-ing]?\n• Would you like me to [bare verb]?\n• Shall I help you with [noun]?\n• Do you need any assistance with [noun]?", cat: "Everyday English", img: "assets/lesson7/image14.png" },
  { id: 12, title: "Structures for Responding", subtitle: "Accepting vs Declining", desc: "• ACCEPTING: 'Yes, please. That would be wonderful.' / 'Thank you so much, that's very kind of you.'\n• DECLINING POLITELY: 'No, thanks. I think I can manage.' / 'That's very kind, but I'm almost finished. Thank you!'", cat: "Everyday English", img: "assets/lesson7/image16.jpeg" },
  { id: 13, title: "Role-play Practice (p. 15)", subtitle: "Situational Scenarios", desc: "Work in pairs and role-play:\nScenario 1: Your friend is struggling to assemble sports equipment in the gym.\nScenario 2: Your partner looks unwell and has a fever during class.\nScenario 3: An elderly neighbor is carrying heavy grocery bags of fresh vegetables.", cat: "Everyday English", img: "assets/lesson7/image18.png", reveal: "Remember: Always maintain eye contact and a warm, supportive tone." },
  { id: 14, title: "CLIL: BIOLOGY", subtitle: "Bacteria and Viruses (p. 16)", desc: "What are the fundamental biological differences between bacteria and viruses?", cat: "CLIL", img: "assets/lesson7/image20.png" },
  { id: 15, title: "CLIL Reading Text", subtitle: "Understanding Microorganisms", desc: "Bacteria are tiny single-celled living organisms. They possess their own cellular structures including a cell wall, membrane, and DNA. Most bacteria are harmless or beneficial, aiding human digestion. Bacterial infections can be treated effectively with antibiotics.\n\nViruses are much smaller than bacteria and are NOT made of cells. They consist of genetic material (DNA or RNA) enclosed inside a protein coat. Viruses cannot reproduce or generate energy on their own—they must invade a living host cell and hijack its machinery. Crucially, antibiotics DO NOT kill viruses. Viral illnesses must be fought by the body's immune system, aided by vaccines and antiviral drugs.", cat: "CLIL", img: "assets/lesson7/image22.png" },
  { id: 16, title: "TASK 1: Comparison Table", subtitle: "Bacteria vs Viruses (p. 16)", desc: "1. LIVING STATUS:\n   • Bacteria: Living organisms\n   • Viruses: Non-living outside host; active only inside living cells\n2. SIZE:\n   • Bacteria: Microscopic (~1-2 micrometers)\n   • Viruses: Sub-microscopic (10 to 100 times smaller than bacteria)\n3. STRUCTURE:\n   • Bacteria: Single cell with cell wall and cytoplasm\n   • Viruses: Genetic code (DNA/RNA) inside a protein capsid (no cells)\n4. TREATMENT:\n   • Bacteria: Antibiotics kill bacteria\n   • Viruses: Antibiotics have NO effect; vaccines prevent, antiviral drugs help\n5. DISEASE EXAMPLES:\n   • Bacteria: Tuberculosis, cholera, food poisoning\n   • Viruses: Influenza (flu), measles, COVID-19, chickenpox", cat: "CLIL", img: "assets/lesson7/image30.png", reveal: "Never prescribe antibiotics for viral infections like the common cold or flu!" },
  { id: 17, title: "CLIL Review Question 1", subtitle: "Disease Identification", desc: "Which of the following diseases is caused by bacteria?\nA. Tuberculosis\nB. Measles\nC. Influenza", cat: "CLIL", img: "assets/lesson7/image33.png", reveal: "👉 Correct: A. Tuberculosis (Lao phổi do vi khuẩn Mycobacterium gây ra)" },
  { id: 18, title: "CLIL Review Question 2", subtitle: "Observation Tool", desc: "Which instrument is required to view a virus?\nA. Naked eyes\nB. Ordinary light microscope\nC. Electron microscope", cat: "CLIL", img: "assets/lesson7/image34.png", reveal: "👉 Correct: C. Electron microscope (Viruses are too small for standard light microscopes)" },
  { id: 19, title: "CLIL Review Question 3", subtitle: "Living Status", desc: "Can viruses reproduce outside of a living host cell?\nA. Yes, in warm water\nB. Only in rich soil\nC. No, they require a host cell", cat: "CLIL", img: "assets/lesson7/image35.png", reveal: "👉 Correct: C. No, they require a host cell" },
  { id: 20, title: "CLIL Review Question 4", subtitle: "Cellular Structure", desc: "Are viruses made of biological cells?\nA. Yes, they have multiple cells\nB. No, they have no cells at all", cat: "CLIL", img: "assets/lesson7/image36.png", reveal: "👉 Correct: B. No, they have no cells at all (acelluar particles)" },
  { id: 21, title: "CLIL Review Question 5", subtitle: "Antibiotic Function", desc: "Why do antibiotics kill bacteria but fail against viruses?\nA. Because antibiotics target bacterial cell walls and bacterial metabolism which viruses do not possess.\nB. Because viruses are too strong.", cat: "CLIL", img: "assets/lesson7/image38.png", reveal: "👉 Correct: A (Antibiotics specifically inhibit bacterial cell wall synthesis and ribosome protein production)" },
  { id: 22, title: "TASK 2: Health Advisory Scenarios", subtitle: "What Advice Would You Give?", desc: "Scenario 1: Your friend has a sore throat and runny nose from a common cold. He wants to take leftover antibiotics from his family cabinet.\n\nAdvice: Strongly advise against it! Common colds are viral. Antibiotics have zero effect on viruses and taking them unnecessarily destroys beneficial gut bacteria and creates dangerous antibiotic-resistant superbugs!", cat: "Production", img: "assets/lesson7/image43.png", reveal: "Explain the science gently: Rest, hydrate, and use soothing remedies instead." },
  { id: 23, title: "Public Health & Pandemics", subtitle: "COVID-19 Case Study (NLS 4.3NC1a)", desc: "How did humanity protect against the SARS-CoV-2 viral pandemic?\n1. Respiratory Protection: High-filtration masks (N95/medical masks)\n2. Hand Hygiene: Washing with soap kills the virus's lipid envelope\n3. Ventilation: Fresh airflow disperses aerosol droplets\n4. Vaccination: mRNA and viral vector vaccines trained antibodies before exposure", cat: "Production", img: "assets/lesson7/image45.png", reveal: "Digital competence: Finding credible public health information (WHO, CDC, MoH)." },
  { id: 24, title: "CONSOLIDATION & WRAP-UP", subtitle: "Lesson Summary", desc: "What have we mastered today?\n• Natural expressions for offering help and replying\n• Core biological differences between bacteria and viruses\n• The critical importance of responsible antibiotic stewardship\n\nHomework:\n- Create a digital infographic comparing bacteria and viruses [NLS 4.3NC1a / Canva].\n- Prepare for Lesson 8: Looking Back & Project.", cat: "Wrap-up", img: "assets/lesson7/image47.png" },
  { id: 25, title: "THANK YOU!", subtitle: "Science for Better Health!", desc: "Stay informed and protect yourself and your community! 🔬🛡️", cat: "Closing", img: "assets/lesson7/image48.png" }
];

window.Lesson7State = {
  currentSlide: 1,
  activeTab: 'clil',
  quizScore: 0
};
