/**
 * Global Success 11 - Unit 1 Lesson 8 (Looking Back & Project)
 * Review & Healthy Habits Posters Project Studio
 * Full Slide Deck & Interactive Project Guide
 */

const LESSON8_SLIDES = [
  { id: 1, title: "GLOBAL SUCCESS 11", subtitle: "UNIT 1: A LONG AND HEALTHY LIFE", desc: "Living Long and Healthy: Key Habits for a Better Life", cat: "Cover", img: "assets/lesson8/image1.jpeg", reveal: "Lesson 8: Looking Back & Project – Healthy Habits Posters" },
  { id: 2, title: "Lesson 8 Outline", subtitle: "Consolidation & Group Project", desc: "• Warm-up: Longevity Science Challenge (10 Research Questions)\n• Looking Back - Pronunciation: Weak vs Strong Forms of Auxiliary Verbs\n• Looking Back - Vocabulary: Collocations & Gap Fill (p. 16)\n• Looking Back - Grammar: Error Correction (Past Simple vs Present Perfect, p. 17)\n• Project Studio: Healthy Habits Posters (NLS 3.1a & 2.4a)\n• Digital Poster Guidelines (Canva, Google Slides, CapCut)\n• Exhibition & Peer Assessment Rubric\n• Unit 1 Wrap-up & Preview of Unit 2", cat: "Agenda", img: "assets/lesson8/image2.png" },
  { id: 3, title: "WARM - UP", subtitle: "Longevity Science Quiz", desc: "Let's explore what scientific longevity studies have revealed about living past 100!", cat: "Warm-up", img: "assets/lesson8/image3.svg" },
  { id: 4, title: "Longevity Question 1", subtitle: "Social Health", desc: "Which factor is most strongly linked with longevity in long-term human studies?\nA. Regular social connections and family ties\nB. Eating only red meat\nC. Sleeping less than 5 hours\nD. Avoiding all exercise", cat: "Warm-up", img: "assets/lesson8/image6.png", reveal: "👉 Correct: A. Regular social connections (The Harvard Study of Adult Development proved close relationships protect both mind and longevity)" },
  { id: 5, title: "Longevity Question 2", subtitle: "Dietary Patterns", desc: "Which type of diet is associated with living longer and fewer chronic illnesses?\nA. Fast-food diet\nB. High-sugar diet\nC. Processed meat diet\nD. Mediterranean / Plant-rich diet", cat: "Warm-up", img: "assets/lesson8/image7.png", reveal: "👉 Correct: D. Mediterranean / Plant-rich diet (Abundant olive oil, vegetables, legumes, and fish)" },
  { id: 6, title: "Longevity Question 3", subtitle: "Cellular Aging", desc: "Which activity has been scientifically shown to slow aging at the cellular level?\nA. Meditation & brisk walking\nB. Skipping breakfast daily\nC. Heavy alcohol consumption\nD. Prolonged sitting", cat: "Warm-up", img: "assets/lesson8/image8.png", reveal: "👉 Correct: A. Meditation & brisk walking (Reduces cortisol and preserves telomere length)" },
  { id: 7, title: "Longevity Question 4", subtitle: "Nutritional Science", desc: "Which type of fat is considered 'good' for cardiovascular longevity?\nA. Trans fats\nB. Unsaturated fats\nC. Saturated fats\nD. Chemically modified fats", cat: "Warm-up", img: "assets/lesson8/image9.png", reveal: "👉 Correct: B. Unsaturated fats (Found in olive oil, nuts, avocados, and salmon)" },
  { id: 8, title: "Longevity Question 5", subtitle: "Telomere Science", desc: "Why is chronic emotional stress harmful to human longevity?\nA. It improves cardiovascular endurance\nB. It increases bone thickness\nC. It shortens telomeres (chromosome protective caps)\nD. It prevents weight gain", cat: "Warm-up", img: "assets/lesson8/image10.png", reveal: "👉 Correct: C. It shortens telomeres, accelerating cellular senescence" },
  { id: 9, title: "Longevity Question 6", subtitle: "Blue Zones", desc: "Which region of the world is famous for having the highest concentration of active centenarians?\nA. Sahara Desert\nB. Blue Zones (e.g., Okinawa, Sardinia, Nicoya, Icaria)\nC. High Arctic\nD. Industrial metropolis", cat: "Warm-up", img: "assets/lesson8/image11.png", reveal: "👉 Correct: B. Blue Zones (Demographic regions where people naturally live past 100)" },
  { id: 10, title: "Longevity Question 7", subtitle: "Harmful Fats", desc: "Which type of fat is considered the MOST dangerous for human arterial health?\nA. Trans fat\nB. Omega-3\nC. Olive oil\nD. Monounsaturated fat", cat: "Warm-up", img: "assets/lesson8/image12.png", reveal: "👉 Correct: A. Trans fat (Artificial trans fats raise LDL and trigger inflammation)" },
  { id: 11, title: "Longevity Question 8", subtitle: "Mortality Risk Factor", desc: "Which of the following is a proven risk factor for premature mortality comparable to smoking?\nA. Drinking green tea\nB. Social isolation and chronic loneliness\nC. Jogging in parks\nD. Adequate sleep", cat: "Warm-up", img: "assets/lesson8/image13.png", reveal: "👉 Correct: B. Social isolation and chronic loneliness" },
  { id: 12, title: "Longevity Question 9", subtitle: "Dietary Research", desc: "Which diet is linked with the lowest lifetime risk of coronary heart disease?\nA. Keto diet with processed meat\nB. Fast-food convenience diet\nC. High-sugar beverage diet\nD. Whole-food, plant-based diet", cat: "Warm-up", img: "assets/lesson8/image14.png", reveal: "👉 Correct: D. Whole-food, plant-based diet" },
  { id: 13, title: "Longevity Question 10", subtitle: "Daily Habits", desc: "Which simple daily routine can add up to 3-5 healthy years to your life?\nA. Brisk walking 30 minutes per day\nB. Watching television 6 hours a day\nC. Sleeping only 4 hours\nD. Skipping all meals", cat: "Warm-up", img: "assets/lesson8/image15.png", reveal: "👉 Correct: A. Brisk walking 30 minutes per day" },
  { id: 14, title: "LOOKING BACK: Pronunciation", subtitle: "Weak vs Strong Forms (p. 16)", desc: "Auxiliary verbs are pronounced in WEAK form in normal connected speech, and STRONG form in short answers or emphatic positions:\n1. 'Have you been examined yet?' ➔ /həv/ (weak)\n   'Yes, I have.' ➔ /hæv/ (strong)\n2. 'Does he work out every day?' ➔ /dəz/ (weak)\n   'Yes, he does.' ➔ /dʌz/ (strong)", cat: "Looking Back", img: "assets/lesson8/image18.png", reveal: "Rule: Sentence initial/internal = weak schwa /ə/; End of sentence or emphatic = full vowel." },
  { id: 15, title: "LOOKING BACK: Vocabulary", subtitle: "Gap Fill Challenge (p. 16)", desc: "Fill in each blank with ONE word from Unit 1:\n1. We need to _______ down on fast food if we want to improve our fitness.\n2. Doing regular squats and push-ups strengthens our _______ and joints.\n3. Eating whole foods and fresh fruits boosts your _______ system.\n4. Average life _______ has risen dramatically due to medical advances.\n5. Doctors prescribe antibiotics only for _______ infections, not viral ones.", cat: "Looking Back", img: "assets/lesson8/image19.png", reveal: "1: cut | 2: muscles | 3: immune | 4: expectancy | 5: bacterial" },
  { id: 16, title: "LOOKING BACK: Grammar", subtitle: "Error Correction (p. 17)", desc: "Find the incorrect part in each sentence and correct it:\n1. My grandfather has gone to hospital last week.\n2. She didn't exercise since she finished her exams.\n3. How long did you have that bad cough?\n4. I have lived in the countryside when I was eight years old.", cat: "Looking Back", img: "assets/lesson8/image20.png", reveal: "1. has gone ➔ went (last week = Past Simple)\n2. didn't exercise ➔ hasn't exercised (since = Present Perfect)\n3. did you have ➔ have you had (ongoing up to present)\n4. have lived ➔ lived (when I was eight = specific past period)" },
  { id: 17, title: "PROJECT STUDIO", subtitle: "Healthy Habits Posters (p. 17)", desc: "Unit 1 Culminating Project: Design an inspiring digital poster promoting a healthy habit for high school students.", cat: "Project", img: "assets/lesson8/image21.png" },
  { id: 18, title: "Project Brief & Collaboration", subtitle: "Team Organization (NLS 2.4a & 3.1a)", desc: "Group Work (4-5 students per team):\n1. SELECT ONE THEME:\n   • 💧 Smart Hydration: 2L Water Challenge\n   • 📱 Digital Sunset: Screen-Free Sleep Sanctuary\n   • 🥗 Rainbow Plate: 5 Fruits & Veggies Daily\n   • 🏃 30-Minute Movement: Daily High School Energy\n2. DESIGN USING DIGITAL TOOLS:\n   • Canva, Google Slides, PowerPoint, or CapCut Infographic\n3. POSTER COMPONENTS:\n   • Catchy Slogan + Scientific 'Why' + 3 Actionable Tips + Graphic Call-to-Action", cat: "Project", img: "assets/lesson8/image22.png", reveal: "Digital competence: Team collaboration using cloud tools and graphic editors." },
  { id: 19, title: "Exhibition & Evaluation Rubric", subtitle: "Assessment Criteria", desc: "How will your poster be evaluated?\n• CONTENT ACCURACY (40%): Scientific evidence, clear health benefits, correct grammar.\n• VISUAL DESIGN (30%): Typography hierarchy, harmonious color palette, high-res images.\n• ORAL PRESENTATION (30%): 2-minute pitch, persuasive delivery, confident answers to questions.", cat: "Project", img: "assets/lesson8/image23.png", reveal: "Exemplary posters will be printed and displayed in the school corridor!" },
  { id: 20, title: "UNIT 1 CONSOLIDATION", subtitle: "Congratulations!", desc: "You have completed Unit 1: A Long and Healthy Life!\n• Vocabulary: Health, nutrition, immunity, workouts, and microorganisms\n• Grammar: Past Simple vs Present Perfect distinctions\n• Pronunciation: Weak and strong auxiliary forms\n• Skills: Reading for life tips, giving exercise instructions, listening to health broadcasts, writing short messages, and CLIL biology.\n\nPreview of Unit 2:\n➔ Unit 2: The Generation Gap (Family values, teen perspectives, modal verbs)!", cat: "Wrap-up", img: "assets/lesson8/image24.png" },
  { id: 21, title: "THANK YOU!", subtitle: "Unit 1 Complete! 🎉", desc: "Keep practicing healthy habits every single day! See you in Unit 2! 🌟", cat: "Closing", img: "assets/lesson8/image1.jpeg" }
];

window.Lesson8State = {
  currentSlide: 1,
  longevityScore: 0,
  selectedProjectTheme: 'hydration'
};
