/**
 * Global Success 11 - Unit 1 Lesson 4 (Speaking)
 * Giving Instructions for an Exercise Routine
 * Full Slide Deck & Interactive Exercise Simulator
 */

const LESSON4_SLIDES = [
  { id: 1, title: "GLOBAL SUCCESS 11", subtitle: "UNIT 1: A LONG AND HEALTHY LIFE", desc: "Living Long and Healthy: Key Habits for a Better Life", cat: "Cover", img: "assets/lesson4/image16.jpeg", reveal: "Lesson 4: Speaking – Giving Instructions for an Exercise Routine" },
  { id: 2, title: "Lesson 4 Outline", subtitle: "Speaking Focus", desc: "• Warm-up: 'Harvest Carrots' Health Quiz (7 Questions)\n• Vocabulary & Postures: squats, star jumps, push-ups, bending, stretching\n• Instructional Language: Sequence Markers (First, Next, Then, Finally)\n• Task 1: Match exercise postures with names\n• Task 2: Read & Complete model instructions for Star Jumps & Squats\n• Task 3: Pair practice: Giving instructions for exercise routines\n• Task 4: Interactive Exercise Simulator & Demo (NLS 2.1NC1a)\n• Consolidation & Homework (Digital Video Recording Assignment)", cat: "Agenda", img: "assets/lesson4/image17.png" },
  { id: 3, title: "WARM - UP", subtitle: "Harvest Carrots Challenge", desc: "Let's review healthy lifestyle habits and earn fresh carrots by answering questions correctly!", cat: "Warm-up", img: "assets/lesson4/image18.png" },
  { id: 4, title: "HARVEST CARROTS", subtitle: "Game Rules", desc: "Answer each question to pull a carrot from the field!\nTest your nutrition and exercise knowledge.", cat: "Warm-up", img: "assets/lesson4/image20.png" },
  { id: 5, title: "Harvest Question 1", subtitle: "Nutrition Check", desc: "What should you look at when choosing food?\nA. the cooking time\nB. the food labels\nC. the package color", cat: "Warm-up", img: "assets/lesson4/image22.png", reveal: "👉 Correct: B. the food labels (Always inspect nutritional info, sugar, and ingredients!)" },
  { id: 6, title: "Harvest Question 2", subtitle: "Diet Check", desc: "Avoid having food with too much salt or _______.\nA. vegetables\nB. fresh fruit\nC. sugar", cat: "Warm-up", img: "assets/lesson4/image24.png", reveal: "👉 Correct: C. sugar (Excessive sugar and sodium cause cardiovascular strain)" },
  { id: 7, title: "Harvest Question 3", subtitle: "Meal Habits", desc: "You should eat a big breakfast and a small dinner.\nA. True\nB. False", cat: "Warm-up", img: "assets/lesson4/image25.png", reveal: "👉 Correct: A. True (A substantial breakfast fuels the day; light dinners support sound sleep)" },
  { id: 8, title: "Harvest Question 4", subtitle: "Fitness Beginning", desc: "How should a person begin exercising if they haven’t been active?\nA. start slowly and regularly\nB. exercise hard everyday\nC. lift the heaviest weights immediately", cat: "Warm-up", img: "assets/lesson4/image26.GIF", reveal: "👉 Correct: A. start slowly and regularly (Prevent injury by building baseline stamina)" },
  { id: 9, title: "Harvest Question 5", subtitle: "Exercise Progression", desc: "When your body is ready and stronger, you can exercise _______.\nA. slower\nB. longer and with more intensity\nC. shorter", cat: "Warm-up", img: "assets/lesson4/image27.GIF", reveal: "👉 Correct: B. longer and with more intensity (Progressive overload improves fitness)" },
  { id: 10, title: "Harvest Question 6", subtitle: "Sleep Science", desc: "You can fall asleep more easily if you do vigorous cardio exercise right before going to bed.\nA. True\nB. False", cat: "Warm-up", img: "assets/lesson4/image28.GIF", reveal: "👉 Correct: B. False (Vigorous late-night workouts raise core temperature and heart rate, delaying sleep)" },
  { id: 11, title: "Harvest Question 7", subtitle: "Sleep Hygiene", desc: "What helps you sleep better at night?\nA. turning off electronic devices early\nB. scrolling social media in bed\nC. drinking energy drinks", cat: "Warm-up", img: "assets/lesson4/image29.GIF", reveal: "👉 Correct: A. turning off electronic devices early (Eliminates blue light interference)" },
  { id: 12, title: "VOCABULARY", subtitle: "Exercise Routine Cues", desc: "Master the key verbs and nouns used to describe workouts.", cat: "Vocabulary", img: "assets/lesson4/image30.png" },
  { id: 13, title: "Exercise Move 1: Squat", subtitle: "Vocabulary Spotlight", desc: "squat /skwɒt/ (n/v): động tác ngồi xổm (nhún đùi)\n• Crouch down with knees bent and back straight.\n• Strengthens quadriceps, hamstrings, and glutes.", cat: "Vocabulary", img: "assets/lesson4/image31.GIF", reveal: "Squats strengthen lower-body muscles and joint stability." },
  { id: 14, title: "Exercise Move 2: Star Jump", subtitle: "Vocabulary Spotlight", desc: "star jump /ˈstɑː dʒʌmp/ (n): động tác nhảy dang tay chân hình sao\n• Jump up into the air while opening arms and legs wide into a star shape.\n• High-energy aerobic exercise for heart and agility.", cat: "Vocabulary", img: "assets/lesson4/image32.GIF", reveal: "Also known as Jumping Jacks." },
  { id: 15, title: "Exercise Move 3: Push-up", subtitle: "Vocabulary Spotlight", desc: "push-up /ˈpʊʃ ʌp/ (n): động tác chống đẩy (hít đất)\n• Lie facing the floor and raise body using arm strength.\n• Builds chest, shoulders, and triceps.", cat: "Vocabulary", img: "assets/lesson4/image33.GIF", reveal: "Push-ups target upper body and core stability." },
  { id: 16, title: "Action Verbs: Posture & Movement", subtitle: "Key Movement Terms", desc: "1. bend /bend/ (v): gập người, cúi cong gối\n2. stretch /stretʃ/ (v): duỗi thẳng, kéo căng cơ\n3. keep your back straight: giữ lưng thẳng\n4. breathe evenly /ˈiːvnli/: thở đều đặn, không nín thở", cat: "Vocabulary", img: "assets/lesson4/image34.png", reveal: "Proper breathing and straight posture prevent lower back strain." },
  { id: 17, title: "TASK 1: Match the Activities", subtitle: "Postures with Names", desc: "Match the images in the textbook with the correct exercise:\nPicture A: Star jumps\nPicture B: Squats\nPicture C: Push-ups", cat: "Practice", img: "assets/lesson4/image35.png", reveal: "Key: Picture A = Star jumps | Picture B = Squats | Picture C = Push-ups" },
  { id: 18, title: "Useful Language: Sequence Markers", subtitle: "Giving Clear Step-by-Step Instructions", desc: "To guide someone through an exercise routine, use ordering adverbs:\n• First, ... (Bắt đầu bằng)\n• Next, ... (Tiếp theo)\n• Then, ... (Sau đó)\n• After that, ... (Kế tiếp)\n• Finally, ... (Cuối cùng)", cat: "Language", img: "assets/lesson4/image36.png", reveal: "Use imperative verbs: Stand, Bend, Lower, Push, Return, Breathe." },
  { id: 19, title: "TASK 2: Star Jumps Instructions", subtitle: "Model Instructional Text", desc: "Complete the instructions for Star Jumps:\n'First, stand with your feet together and arms at your sides.\nNext, bend your knees slightly and jump up.\nAt the same time, spread your legs wide and bring your arms above your head.\nFinally, jump back to the starting position and land softly.'", cat: "Practice", img: "assets/lesson4/image37.png", reveal: "Gaps: 1. feet | 2. bend | 3. spread | 4. position | 5. softly" },
  { id: 20, title: "Model Instructions: Squats", subtitle: "Step-by-Step Execution", desc: "How to perform a proper Squat:\n• First: Stand with feet shoulder-width apart.\n• Next: Slowly bend your knees and push hips back like sitting in a chair.\n• Form cue: Keep your back straight, chest lifted, and knees tracking over toes.\n• Finally: Press through your heels to return to standing position.", cat: "Practice", img: "assets/lesson4/image38.png", reveal: "Inhale when lowering, exhale when pushing up." },
  { id: 21, title: "Model Instructions: Push-ups", subtitle: "Step-by-Step Execution", desc: "How to perform a Push-up:\n• First: Place hands slightly wider than shoulder-width, forming a straight plank.\n• Next: Lower your chest towards the floor by bending elbows at 45 degrees.\n• Form cue: Keep core tight; don't let hips sag.\n• Finally: Push firmly through your palms to return to the top.", cat: "Practice", img: "assets/lesson4/image39.png", reveal: "Beginners can start with knees on the floor." },
  { id: 22, title: "TASK 3: Pair Practice Routine", subtitle: "Leader & Performer", desc: "Student A acts as the Fitness Trainer and delivers step-by-step instructions.\nStudent B listens and performs the routine.\nThen switch roles!", cat: "Speaking", img: "assets/lesson4/image40.png", reveal: "Trainer tip: Speak clearly, pause between steps, and check partner's posture." },
  { id: 23, title: "Trainer Script Template", subtitle: "Sample Delivery", desc: "'Hello everyone! Today I will demonstrate the 3-step squat routine.\nFirst, make sure your feet are shoulder-width apart.\nNext, bend your knees and keep your back straight.\nMake sure your knees do not cross beyond your toes.\nFinally, push back up and breathe out smoothly!'", cat: "Speaking", img: "assets/lesson4/image41.png", reveal: "Clear vocal cues improve partner safety and motivation." },
  { id: 24, title: "TASK 4: Class Demonstration", subtitle: "Group Showcase", desc: "Take turns demonstrating the exercise routine to the rest of the group.\nClassmates do the movements along with your verbal cues!\nEncourage energetic, positive instructions.", cat: "Speaking", img: "assets/lesson4/image42.png", reveal: "NLS 2.1NC1a: Physical coordination guided by digital audio-visual prompts." },
  { id: 25, title: "Peer Evaluation Rubric", subtitle: "How Was the Demonstration?", desc: "1. Clarity of speech & volume: ⭐⭐⭐⭐⭐\n2. Correct sequence markers (First, Next, Finally): ⭐⭐⭐⭐⭐\n3. Posture guidance & safety warnings: ⭐⭐⭐⭐⭐\n4. Timing & rhythm: ⭐⭐⭐⭐⭐", cat: "Speaking", img: "assets/lesson4/image43.png", reveal: "Constructive feedback helps refine physical demonstration skills." },
  { id: 26, title: "CONSOLIDATION & WRAP-UP", subtitle: "Lesson Takeaways", desc: "What have we achieved in Lesson 4?\n• Mastered names and postures for squats, star jumps, and push-ups\n• Applied sequence markers (First, Next, Then, Finally) fluently\n• Practiced leading and following spoken fitness instructions\n\nDigital Homework (NLS 2.1NC1a):\n- Use your smartphone or tablet to record a 60-second video demonstrating your chosen exercise routine with English spoken guidance.\n- Share your video to the class learning group.", cat: "Wrap-up", img: "assets/lesson4/image44.png" },
  { id: 27, title: "THANK YOU!", subtitle: "Keep Moving & Stay Fit!", desc: "Remember: Daily movement is the best medicine for body and mind! 💪🔥", cat: "Closing", img: "assets/lesson4/image45.png" }
];

window.Lesson4State = {
  currentSlide: 1,
  activeExercise: 'squats',
  simulatorStep: 0,
  carrotsHarvested: 0
};
